begin;
create temporary table business_ids(name text primary key,id uuid default gen_random_uuid());
insert into business_ids(name) values('client'),('contractor'),('stranger'),('project'),('quote');
grant select on business_ids to authenticated,anon;
create function pg_temp.bid(key text) returns uuid language sql as $$select id from pg_temp.business_ids where name=key$$;
create function pg_temp.check_business(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label; end if; end $$;
create function pg_temp.deny_business(command text) returns void language plpgsql as $$declare denied boolean:=false;begin begin execute command;exception when insufficient_privilege or check_violation then denied:=true;end;if not denied then raise exception 'Unauthorized operation succeeded: %',command;end if;end $$;
insert into auth.users(id,email) select id,'business-test-'||id||'@example.invalid' from business_ids where name in ('client','contractor','stranger');
insert into public.rd_profiles(id,role,display_name,city,latitude,longitude,services,radius_km) select id,case when name='contractor' then 'contractor' else 'client' end,name,'Laval',45,-73,case when name='contractor' then array['general'] else '{}'::text[] end,50 from business_ids where name in ('client','contractor','stranger');
insert into public.rd_projects(id,client_id,title,service,description,budget,timing,city,latitude,longitude) values(pg_temp.bid('project'),pg_temp.bid('client'),'Business fixture','plumbing','Fixture description','1000','Flexible','Laval',45,-73);
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.bid('contractor')::text,true);
insert into public.rd_business_pages(id,tagline) values(auth.uid(),'Private business fixture');
insert into public.rd_portfolio(contractor_id,title,after_path) values(auth.uid(),'Portfolio fixture',auth.uid()||'/abcdef.jpg');
insert into storage.objects(bucket_id,name) values('rd-business-media',auth.uid()||'/abcdef.jpg');
select pg_temp.check_business((select count(*) from public.rd_business_pages where id=auth.uid())=1,'Owner reads');
select pg_temp.deny_business(format('insert into public.rd_portfolio(contractor_id,title,after_path) values(%L,''Foreign photo'',%L)',auth.uid(),pg_temp.bid('client')||'/abcdef.jpg'));
select pg_temp.deny_business(format('insert into storage.objects(bucket_id,name) values(''rd-business-media'',%L)',pg_temp.bid('client')||'/abcdef.jpg'));
select public.rd_save_business_changes('{"tagline":"Atomic profile"}',jsonb_build_object('id',pg_temp.bid('project'),'title','Atomic realization','after_path',auth.uid()||'/abcdef.jpg'));
select public.rd_save_business_changes('{"tagline":"Retry profile"}',jsonb_build_object('id',pg_temp.bid('project'),'title','Atomic realization updated','after_path',auth.uid()||'/abcdef.jpg'));
select pg_temp.check_business((select count(*) from public.rd_portfolio where id=pg_temp.bid('project'))=1,'Retry does not duplicate realization');
select pg_temp.deny_business(format('select public.rd_save_business_changes(%L::jsonb,%L::jsonb)','{"tagline":"Must roll back"}',jsonb_build_object('id',gen_random_uuid(),'title','Bad image','after_path',pg_temp.bid('client')||'/abcdef.jpg')::text));
select pg_temp.check_business((select tagline from public.rd_business_pages where id=auth.uid())='Retry profile','Invalid realization rolls back presentation');
select set_config('request.jwt.claim.sub',pg_temp.bid('client')::text,true);
select pg_temp.check_business((select count(*) from public.rd_business_pages where id=pg_temp.bid('contractor'))=0,'Not visible before quote');
select pg_temp.check_business((select count(*) from storage.objects where bucket_id='rd-business-media' and name=pg_temp.bid('contractor')||'/abcdef.jpg')=0,'Photo private before quote');
select set_config('request.jwt.claim.sub',pg_temp.bid('contractor')::text,true);
insert into public.rd_quotes(id,project_id,contractor_id,amount,duration,start_date,message) values(pg_temp.bid('quote'),pg_temp.bid('project'),auth.uid(),100,'1 jour',current_date,'Business security fixture');
select set_config('request.jwt.claim.sub',pg_temp.bid('client')::text,true);
select pg_temp.check_business((select count(*) from public.rd_business_pages where id=pg_temp.bid('contractor'))=1,'Counterpart reads profile');
select pg_temp.check_business((select count(*) from public.rd_portfolio where contractor_id=pg_temp.bid('contractor'))=2,'Counterpart reads portfolio');
select pg_temp.check_business((select count(*) from storage.objects where bucket_id='rd-business-media' and name=pg_temp.bid('contractor')||'/abcdef.jpg')=1,'Counterpart reads image');
select pg_temp.deny_business(format('insert into public.rd_business_pages(id) values(%L)',auth.uid()));
select pg_temp.deny_business('select public.rd_save_business_changes(''{"tagline":"Client forgery"}''::jsonb)');
with changed as(update public.rd_business_pages set bio='forged' where id=pg_temp.bid('contractor') returning id) select pg_temp.check_business(count(*)=0,'Counterpart cannot edit') from changed;
select pg_temp.deny_business(format('insert into public.rd_portfolio(contractor_id,title,after_path) values(%L,''Client fake portfolio'',%L)',auth.uid(),auth.uid()||'/abcdef.jpg'));
select set_config('request.jwt.claim.sub',pg_temp.bid('stranger')::text,true);
select pg_temp.check_business((select count(*) from public.rd_business_pages where id=pg_temp.bid('contractor'))=0,'Stranger profile hidden');
select pg_temp.check_business((select count(*) from public.rd_portfolio where contractor_id=pg_temp.bid('contractor'))=0,'Stranger portfolio hidden');
select pg_temp.check_business((select count(*) from storage.objects where bucket_id='rd-business-media' and name=pg_temp.bid('contractor')||'/abcdef.jpg')=0,'Stranger media hidden');
select pg_temp.deny_business('truncate public.rd_business_pages');
set local role anon;
select pg_temp.deny_business('select * from public.rd_business_pages');
select pg_temp.deny_business('select * from public.rd_portfolio');
select pg_temp.deny_business('select public.rd_save_business_changes(''{}''::jsonb)');
reset role;
rollback;
select 'PASS: business profile, portfolio and storage owner/counterpart/stranger isolation, client write denial, foreign photo paths, anonymous denial; fixtures rolled back' as business_tests;
