const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require(process.env.RD_JSDOM_PATH||'jsdom');
const core=require('../app/core.js');
// jsdom does not compute CSS layers/layout. Guard the actual cascade boundary
// separately: unlayered chat styles cannot beat important page styles in a layer.
const designCSS=fs.readFileSync(path.join(__dirname,'../app/projeko-design.css'),'utf8'),layerBlocks=[];
for(const match of designCSS.matchAll(/@layer projekodesign\s*\{/g)){let depth=1,end=match.index+match[0].length;for(;end<designCSS.length&&depth;end++){if(designCSS[end]==='{')depth++;else if(designCSS[end]==='}')depth--;}layerBlocks.push(designCSS.slice(match.index,end));}
const chatLayer=layerBlocks.find(block=>block.includes('#clientChat#clientChat > .rd-live-detail'));
assert.ok(chatLayer,'Chat wrapper containment must be in the same important layer as page styles');
const wrapperRules=/#clientChat#clientChat > \.rd-live-detail\{([^}]+)\}/.exec(chatLayer)[1];
for(const declaration of ['height:100%!important','min-height:0!important','padding:0!important','margin:0!important','max-width:none!important','overflow:hidden!important'])assert.ok(wrapperRules.includes(declaration),'Chat wrapper must reset '+declaration);
const users={client:{id:'client',email:'client@example.invalid'},plumber:{id:'plumber',email:'plumber@example.invalid'},electrician:{id:'electrician',email:'electrician@example.invalid'},general:{id:'general',email:'general@example.invalid'}};
const tables={rd_profiles:Object.entries(users).map(([k,v])=>({id:v.id,role:k==='client'?'client':'contractor',display_name:k,company_name:k==='client'?'':k,city:'Laval',latitude:45.56995,longitude:-73.692,services:k==='client'?[]:[k==='plumber'?'plumbing':k==='electrician'?'electrical':'general'],radius_km:50,rbq:''})),rd_projects:[],rd_quotes:[],rd_messages:[],rd_project_photos:[],rd_account_details:[]};
tables.rd_business_pages=[];tables.rd_portfolio=[];
let current=users.client,authCallback,queryDelay=null,queryBefore=null;const intervals=[];const channels=[];
const motionBoot=process.argv.includes('--motion');const transitionSnapshots=[];
const recoveryBoot=process.argv.includes('--recovery'),signupBoot=process.argv.includes('--signup'),loginBoot=process.argv.includes('--login'),citiesOffline=process.argv.includes('--cities-offline');if(signupBoot||loginBoot)current=null;const signupCalls=[];let passwordUpdates=0;
const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),{url:'https://projeko.vercel.app/#clientDashboard',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
w.visualViewport=Object.assign(new w.EventTarget(),{height:800,offsetTop:0});
w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=function(){};w.confirm=()=>true;w.fetch=async()=>{if(citiesOffline)throw Error('Failed to fetch');return ({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(__dirname,'../app/cities.json')))});};w.setInterval=(fn,ms)=>{intervals.push({fn,ms});return intervals.length;};
if(motionBoot)w.document.startViewTransition=callback=>{const updated=Promise.resolve().then(callback).then(()=>{transitionSnapshots.push({route:w.location.hash,text:w.document.querySelector(w.location.hash)?.textContent||''});});return {ready:updated,updateCallbackDone:updated,finished:updated,skipTransition(){}};};
class Query {
 upsert(row){this.mode='upsert';this.row=row;return this;}
 constructor(table){this.table=table;this.filters=[];this.mode='select';this.one=false;}
 select(){return this;}eq(k,v){this.filters.push(r=>r[k]===v);return this;}in(k,vs){this.filters.push(r=>vs.includes(r[k]));return this;}order(){return this;}limit(n){this.max=n;return this;}maybeSingle(){this.one=true;return this;}single(){this.one=true;return this;}insert(rows){this.mode='insert';this.rows=Array.isArray(rows)?rows:[rows];return this;}update(row){this.mode='update';this.row=row;return this;}
 then(resolve,reject){return Promise.resolve().then(async()=>{
 if(queryBefore)await queryBefore(this);if(this.mode==='insert'&&this.rows.some(r=>r.id&&tables[this.table].some(x=>x.id===r.id)))throw Object.assign(Error('duplicate key'),{code:'23505'});let rows=tables[this.table];if(this.mode==='upsert'){let row=rows.find(x=>x.id===this.row.id);if(row)Object.assign(row,this.row);else{row={...this.row};rows.push(row);}rows=[row];}else if(this.mode==='insert'){rows=this.rows.map(r=>({...r,id:r.id||w.crypto.randomUUID(),created_at:new Date().toISOString(),...(!r.status&&['rd_projects','rd_quotes'].includes(this.table)?{status:this.table==='rd_projects'?'open':'pending'}:{})}));tables[this.table].push(...rows);}else if(this.mode==='update'){rows=rows.filter(r=>this.filters.every(f=>f(r)));rows.forEach(r=>Object.assign(r,this.row));}
 if(this.mode==='select'){if(this.table==='rd_projects'){const p=tables.rd_profiles.find(p=>p.id===current?.id);rows=rows.filter(r=>r.client_id===current?.id||core.matches(p,r)||tables.rd_quotes.some(q=>q.project_id===r.id&&q.contractor_id===current?.id));}else if(this.table==='rd_quotes')rows=rows.filter(q=>q.contractor_id===current?.id||tables.rd_projects.some(p=>p.id===q.project_id&&p.client_id===current?.id));rows=rows.filter(r=>this.filters.every(f=>f(r)));}
 if(this.max)rows=rows.slice(0,this.max);if(queryDelay)await queryDelay(this);return {data:this.one?(rows[0]||null):rows,error:null};
 }).then(resolve,reject);}
}
const db={channel:name=>{const ch={name,removed:false,on(type,filter,callback){this.filter=filter;this.callback=callback;return this;},subscribe(status){this.status=status;channels.push(this);return this;}};return ch;},removeChannel:async ch=>{ch.removed=true;},from:t=>new Query(t),auth:{getSession:async()=>{if(recoveryBoot)authCallback?.('PASSWORD_RECOVERY',{user:current});return {data:{session:{user:current}},error:null};},updateUser:async()=>{passwordUpdates++;return {data:{user:current},error:null};},onAuthStateChange:fn=>{authCallback=fn;return {data:{subscription:{unsubscribe(){}}}};},signInWithPassword:async payload=>{if(payload.password!=='TestingOnly123!')return {data:{},error:{message:'Invalid login credentials'}};current=Object.values(users).find(u=>u.email===payload.email);if(!current)return {data:{},error:{message:'Invalid login credentials'}};return {data:{user:current,session:{user:current}},error:null};},signUp:async payload=>{signupCalls.push(payload);return {data:{session:null,user:null},error:null};},signOut:async()=>{current=null;authCallback('SIGNED_OUT',null);return {error:null};}},storage:{from:()=>({createSignedUrls:async()=>({data:[]})})},rpc:async(name,args)=>{if(name==='rd_save_business_changes'){const owner=current.id;let page=tables.rd_business_pages.find(x=>x.id===owner);if(!page){page={id:owner};tables.rd_business_pages.push(page);}Object.assign(page,args.presentation);if(args.realization){let item=tables.rd_portfolio.find(x=>x.id===args.realization.id);if(item)Object.assign(item,args.realization);else tables.rd_portfolio.push({...args.realization,contractor_id:owner});}return {data:null,error:null};}if(name==='rd_accept_quote'){const q=tables.rd_quotes.find(q=>q.id===args.quote),p=tables.rd_projects.find(p=>p.id===q.project_id);assert.equal(p.client_id,current.id);assert.equal(p.status,'open');tables.rd_quotes.filter(x=>x.project_id===p.id).forEach(x=>x.status=x.id===q.id?'accepted':'declined');p.status='accepted';p.accepted_quote_id=q.id;return {data:p.id};}const p=tables.rd_projects.find(p=>p.id===args.project);const owner=p.client_id===current.id,participant=tables.rd_quotes.some(q=>q.id===p.accepted_quote_id&&q.contractor_id===current.id);assert.ok(owner||participant);assert.ok((args.next_status==='in_progress'&&p.status==='accepted')||(args.next_status==='completed'&&owner&&['accepted','in_progress'].includes(p.status))||(args.next_status==='archived'&&owner&&p.status==='open'));p.status=args.next_status;return {data:null};}};
w.supabase={createClient:()=>db};w.eval(fs.readFileSync(path.join(__dirname,'../app/core.js'),'utf8'));w.eval(fs.readFileSync(path.join(__dirname,'../app/marketplace.js'),'utf8'));
const pause=()=>new Promise(r=>setTimeout(r,35));async function route(id){w.location.hash=id;await pause();}
function fill(id,v){const el=w.document.getElementById(id);el.value=v;el.dispatchEvent(new w.Event('input',{bubbles:true}));}async function click(selector){const e=w.document.querySelector(selector);assert.ok(e,selector);e.click();await pause();}
async function switchUser(key){current=users[key];authCallback('SIGNED_IN',{user:current});await pause();}
function noError(){assert.equal(w.document.querySelector('.rd-live-error'),null,w.document.querySelector('.rd-live-error')?.textContent);}
const businessUploads=[],drawCalls=[];w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.Image=class{constructor(){this.width=600;this.height=400;}async decode(){}};w.HTMLCanvasElement.prototype.getContext=()=>({drawImage(...args){drawCalls.push(args);}});w.HTMLCanvasElement.prototype.toBlob=function(fn){fn(new w.Blob(['fixture'],{type:'image/jpeg'}));};
db.storage.from=()=>({upload:async(path,blob)=>{businessUploads.push({path,type:blob.type});return {data:{path},error:null};},createSignedUrl:async path=>({data:{signedUrl:'https://example.invalid/'+path}}),remove:async()=>({data:[],error:null}),createSignedUrls:async paths=>({data:paths.map(path=>({path,signedUrl:'https://example.invalid/'+path}))})});
function choosePhoto(id){Object.defineProperty(w.document.getElementById(id),'files',{configurable:true,value:[new w.File(['fixture'],'fixture.png',{type:'image/png'})]});}
(async()=>{
 if(citiesOffline){await pause();assert.match(w.document.getElementById('clientDashboard').textContent,/Aucun projet en cours/);assert.match(w.document.getElementById('rd-live-notice').textContent,/suggestions de villes/);console.log('PASS: city lookup outage does not disable authenticated navigation');dom.window.close();return;}
 if(loginBoot){await pause();await route('loginClient');assert.equal(w.document.querySelector('#loginClient a.back').textContent,'‹ Retour');fill('rd-login-client-email','client@example.invalid');fill('rd-login-client-password','WrongPassword!');w.document.getElementById('rd-login-client-password').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await pause();assert.match(w.document.querySelector('.rd-live-error').textContent,/Courriel ou mot de passe incorrect/);assert.equal(current,null);fill('rd-login-client-email','plumber@example.invalid');fill('rd-login-client-password','TestingOnly123!');await click('#loginClient a.primary');assert.equal(current,null);assert.match(w.document.querySelector('.rd-live-error').textContent,/compte entrepreneur/);fill('rd-login-client-email','client@example.invalid');fill('rd-login-client-password','TestingOnly123!');w.document.getElementById('rd-login-client-password').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await pause();assert.equal(w.location.hash,'#clientDashboard');noError();await click('#clientDashboard [data-logout]');await route('loginPro');fill('rd-login-contractor-email','plumber@example.invalid');fill('rd-login-contractor-password','TestingOnly123!');w.document.getElementById('rd-login-contractor-password').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await pause();assert.equal(w.location.hash,'#contractorFeed');noError();console.log('PASS: invalid credentials, wrong-role logout and Enter-key login for both account roles');dom.window.close();return;}
 if(signupBoot){await pause();await route('client');await click('#client a.primary');assert.equal(signupCalls.length,0);assert.match(w.document.querySelector('.rd-live-error').textContent,/prénom et votre nom/);fill('rd-signup-given-name','Alex');fill('rd-signup-family-name','Exemple');fill('rd-signup-address-level2','Terrebonne');fill('rd-signup-email','alex@example.invalid');fill('rd-signup-new-password','TestingOnly123!');fill('rd-signup-confirm-password','Mismatch123!');w.document.querySelector('#client .terms input').checked=true;await click('#client a.primary');assert.equal(signupCalls.length,0);assert.match(w.document.querySelector('.rd-live-error').textContent,/identiques/);fill('rd-signup-confirm-password','TestingOnly123!');await click('#client a.primary');assert.equal(signupCalls.length,1);assert.equal(signupCalls[0].options.data.initial_profile.role,'client');assert.equal(signupCalls[0].options.data.initial_profile.city,'Terrebonne');assert.equal(w.location.hash,'#loginClient');assert.equal(w.document.getElementById('rd-signup-new-password').value,'');
 await route('pro1');fill('rd-pro1-field-1','Sam');fill('rd-pro1-field-2','Exemple');fill('rd-pro1-field-3','sam@example.invalid');fill('rd-pro1-field-5','TestingOnly123!');fill('rd-pro1-field-6','TestingOnly123!');await click('#pro1 a.primary');assert.equal(w.location.hash,'#pro2');await click('#pro2 a.primary');assert.match(w.document.querySelector('.rd-live-error').textContent,/entreprise/);fill('rd-pro2-field-1','Entreprise Exemple');fill('rd-pro2-field-5','Terrebonne');await click('#pro2 a.primary');await click('#services a.primary');assert.match(w.document.querySelector('.rd-live-error').textContent,/au moins un service/);w.document.getElementById('svc-plomb').checked=true;await click('#services a.primary');assert.equal(w.location.hash,'#territory');fill('rd-territory-field-2','0');await click('#territory a.primary');assert.equal(signupCalls.length,1);fill('rd-territory-field-2','25');await click('#territory a.primary');assert.equal(signupCalls.length,2);assert.equal(signupCalls[1].options.data.initial_profile.role,'contractor');assert.deepEqual([...signupCalls[1].options.data.initial_profile.services],['plumbing']);assert.equal(signupCalls[1].options.data.initial_profile.radius_km,25);assert.equal(w.location.hash,'#loginPro');assert.equal(w.document.getElementById('rd-pro1-field-5').value,'');console.log('PASS: client and contractor signup validation, payloads, confirmation redirect and credential cleanup');dom.window.close();return;}
 if(recoveryBoot){await pause();assert.equal(w.location.hash,'#resetPassword','Recovery event during getSession must not be lost');fill('rd-live-new-password','TestingOnly123!');w.document.getElementById('rd-live-reset').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();assert.equal(passwordUpdates,1);assert.equal(w.location.hash,'#clientDashboard');assert.equal(w.document.getElementById('rd-live-new-password'),null);console.log('PASS: startup password recovery, successful reset and secret removal');dom.window.close();return;}
 await pause();assert.match(w.document.querySelector('#clientDashboard').textContent,/Aucun projet en cours/);await click('#clientDashboard a[href="#newProject"]');await click('[data-service="plumbing"]');fill('rd80ProjectName','Remplacement robinet');fill('rd62Description','Remplacer le robinet de la cuisine et vérifier les tuyaux.');await click('#projectDetails .rd52-next');await click('#rd62BudgetOptions a');await click('#rd62TimingOptions a');fill('rd62City','Laval');fill('rd62Postal','H7X 0A0');await click('#projectLocation .rd52-next');assert.match(w.document.querySelector('#rd-live-review').textContent,/Remplacement robinet/);w.document.getElementById('rd72Publish').click();w.document.getElementById('rd72Publish').click();await pause();noError();assert.equal(tables.rd_projects.length,1);assert.match(w.document.querySelector('#clientProjectDetail').textContent,/Aucune soumission/);
 const incomingId=w.crypto.randomUUID();tables.rd_quotes.push({id:incomingId,project_id:tables.rd_projects[0].id,contractor_id:users.plumber.id,amount:325,status:'pending',created_at:new Date().toISOString()});w.dispatchEvent(new w.Event('focus'));await pause();assert.match(w.document.getElementById('rd-quote-notice').textContent,/325/);await click('[data-dismiss-quotes]');assert.equal(w.document.getElementById('rd-quote-notice'),null);w.dispatchEvent(new w.Event('focus'));await pause();assert.equal(w.document.getElementById('rd-quote-notice'),null);tables.rd_quotes.splice(tables.rd_quotes.findIndex(q=>q.id===incomingId),1);

 await switchUser('electrician');await route('contractorFeed');assert.match(w.document.querySelector('#contractorFeed').textContent,/Aucun projet pour le moment/);
 await switchUser('general');await route('contractorFeed');assert.equal(w.document.querySelectorAll('#contractorFeed [data-project]').length,1);
 await switchUser('plumber');await route('contractorFeed');assert.equal(w.document.querySelectorAll('#contractorFeed [data-project]').length,1);await click('#contractorFeed [data-project]');await click('#contractorProject a[href="#contractorBid"]');fill('rd-bid-amount','475');fill('rd-bid-duration','1 journée');fill('rd-bid-date','2026-11-15');fill('rd-bid-message','Installation du robinet, matériel et déplacement inclus.');await route('contractorProject');await route('contractorBid');assert.equal(w.document.getElementById('rd-bid-amount').value,'475');assert.match(w.document.getElementById('rd-bid-message').value,/Installation/);authCallback('TOKEN_REFRESHED',{user:current});await pause();assert.equal(w.document.getElementById('rd-bid-amount').value,'475');w.document.getElementById('rd-live-bid').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(tables.rd_quotes.length,1);await route('contractorQuotes');assert.match(w.document.querySelector('#contractorQuotes').textContent,/475/);
 await switchUser('client');assert.match(w.document.getElementById('rd-quote-notice').textContent,/Nouvelle soumission reçue/);assert.match(w.document.getElementById('rd-quote-notice').textContent,/475/);await route('clientProjects');await click('#clientProjects [data-project]');assert.match(w.document.querySelector('#clientProjectDetail').textContent,/Soumissions reçues \(1\)/);await click('#clientProjectDetail [data-quote]');assert.equal(w.document.getElementById('rd-quote-notice'),null);await switchUser('plumber');assert.equal(w.document.getElementById('rd-quote-notice'),null);await switchUser('client');assert.equal(w.document.getElementById('rd-quote-notice'),null);await click('[data-accept]');assert.equal(tables.rd_projects[0].status,'open');await click('[data-accept-cancel]');assert.equal(tables.rd_projects[0].status,'open');await click('[data-accept]');await click('[data-accept-confirm]');noError();assert.equal(tables.rd_projects[0].status,'accepted');assert.match(w.document.querySelector('#quoteAccepted').textContent,/Entrepreneur choisi/);
 await route('quoteDetail');await click('[data-progress="in_progress"]');assert.equal(tables.rd_projects[0].status,'in_progress');await click('#quoteDetail a[href="#clientChat"]');fill('rd-live-message','Bonjour, à quelle heure êtes-vous disponible ?');const typed=w.document.getElementById('rd-live-message');typed.focus();authCallback('TOKEN_REFRESHED',{user:current});await pause();assert.equal(w.document.getElementById('rd-live-message'),typed);assert.equal(w.document.activeElement,typed);await route('clientMessages');await click('#clientMessages [data-quote]');assert.equal(w.document.getElementById('rd-live-message').value,'Bonjour, à quelle heure êtes-vous disponible ?');w.document.getElementById('rd-live-chat-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();assert.equal(tables.rd_messages.length,1);assert.match(w.document.querySelector('#rd-live-chat-messages').textContent,/Bonjour/);
 // Keyboard resizing and message refresh must not drag someone reading older messages.
 const scrollHost=w.document.getElementById('rd-live-chat-messages'),composeInput=w.document.getElementById('rd-live-message');Object.defineProperty(scrollHost,'scrollHeight',{configurable:true,get:()=>1000});Object.defineProperty(scrollHost,'clientHeight',{configurable:true,get:()=>300});scrollHost.scrollTop=150;composeInput.focus();await pause();assert.equal(scrollHost.scrollTop,150,'Focusing the composer preserves the message being read');w.visualViewport.height=450;w.visualViewport.offsetTop=30;w.visualViewport.dispatchEvent(new w.Event('resize'));await pause();assert.equal(scrollHost.scrollTop,150,'Keyboard resize preserves older message position');assert.equal(w.document.getElementById('clientChat').style.height,'450px');assert.equal(w.document.getElementById('clientChat').style.top,'30px');w.visualViewport.offsetTop=0;
 // Simulate the browser resetting scroll when replacing all message rows.
 const htmlDescriptor=Object.getOwnPropertyDescriptor(w.Element.prototype,'innerHTML');Object.defineProperty(scrollHost,'innerHTML',{configurable:true,get(){return htmlDescriptor.get.call(this);},set(value){htmlDescriptor.set.call(this,value);this.scrollTop=0;}});tables.rd_messages.push({id:'scroll-incoming',quote_id:tables.rd_quotes[0].id,sender_id:'plumber',body:'Message reçu pendant la lecture',created_at:new Date().toISOString()});intervals.find(x=>x.ms===15000).fn();await pause();assert.equal(scrollHost.scrollTop,150,'Incoming message preserves reading position');
 // Sending keeps the keyboard focused and the send icon stable during a slow write.
 fill('rd-live-message','Deuxième message sans saut');const send=w.document.querySelector('.pj-chat-send'),pointer=new w.Event('pointerdown',{bubbles:true,cancelable:true});send.dispatchEvent(pointer);assert.equal(pointer.defaultPrevented,true);let releaseSend;const sendGate=new Promise(r=>releaseSend=r);queryDelay=q=>q.table==='rd_messages'&&q.mode==='insert'?sendGate:null;w.document.getElementById('rd-live-chat-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();assert.equal(w.document.activeElement,composeInput);assert.equal(send.textContent,'↑');assert.match(scrollHost.textContent,/Envoi…/);assert.equal(composeInput.value,'');assert.equal(send.disabled,false);releaseSend();queryDelay=null;await pause();assert.equal(w.document.activeElement,composeInput);assert.equal(scrollHost.scrollTop,1000);assert.equal(send.hasAttribute('aria-busy'),false);assert.equal(composeInput.value,'');w.visualViewport.height=800;
 // Incremental updates retain existing row nodes, and Realtime delivers without a polling tick.
 const firstBubble=scrollHost.querySelector('[data-message-id]'),realtime=channels.at(-1),rt={id:'realtime-immediate',quote_id:tables.rd_quotes[0].id,sender_id:'plumber',body:'Réception instantanée',created_at:new Date().toISOString()};realtime.callback({new:rt});await pause();assert.match(scrollHost.textContent,/Réception instantanée/);assert.equal(scrollHost.querySelector('[data-message-id]'),firstBubble);realtime.callback({new:rt});await pause();assert.equal(scrollHost.querySelectorAll('[data-message-id="realtime-immediate"]').length,1);
 // Multiple quick sends stay visible immediately, even before either network response.
 let releaseQuick;const quickGate=new Promise(r=>releaseQuick=r);queryBefore=q=>q.table==='rd_messages'&&q.mode==='insert'?quickGate:null;
 for(const body of ['Rapide un','Rapide deux']){fill('rd-live-message',body);w.document.getElementById('rd-live-chat-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
 assert.match(scrollHost.textContent,/Rapide un/);assert.match(scrollHost.textContent,/Rapide deux/);assert.equal(composeInput.value,'');releaseQuick();queryBefore=null;await pause();assert.equal(tables.rd_messages.filter(m=>/^Rapide /.test(m.body)).length,2);
 // Failed writes retain their message and retry with the same ID, never duplicating a delivered message.
 let failWrite=true;queryBefore=q=>{if(failWrite&&q.table==='rd_messages'&&q.mode==='insert'){failWrite=false;throw Error('Failed to fetch');}};
 fill('rd-live-message','À relancer sans perte');w.document.getElementById('rd-live-chat-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();const retry=scrollHost.querySelector('[data-chat-retry]');assert.ok(retry);const retryId=retry.dataset.chatRetry;fill('rd-live-message','Nouveau brouillon conservé');queryBefore=null;await click('[data-chat-retry]');assert.equal(tables.rd_messages.filter(m=>m.id===retryId).length,1);assert.equal(composeInput.value,'Nouveau brouillon conservé');assert.equal(scrollHost.querySelector('[data-chat-retry]'),null);
 // A dropped acknowledgement is reconciled with the stored ID instead of offering a duplicate retry.
 let ambiguous=true;queryDelay=q=>{if(ambiguous&&q.table==='rd_messages'&&q.mode==='insert'){ambiguous=false;throw Error('Failed to fetch');}};fill('rd-live-message','Livré malgré réponse perdue');w.document.getElementById('rd-live-chat-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();queryDelay=null;assert.equal(scrollHost.querySelector('[data-chat-retry]'),null);assert.equal(tables.rd_messages.filter(m=>m.body==='Livré malgré réponse perdue').length,1);
 // A failed signed photo must not prevent text from being received.
 const signedFrom=db.storage.from;db.storage.from=b=>({...signedFrom(b),createSignedUrl:async()=>{throw Error('Failed to fetch');}});realtime.callback({new:{...rt,id:'photo-unavailable',body:'Texte reste lisible',attachment_path:'plumber/unavailable.jpg',attachment_type:'image/jpeg'}});await pause();assert.match(scrollHost.textContent,/Texte reste lisible/);assert.match(scrollHost.textContent,/Pièce jointe indisponible/);db.storage.from=signedFrom;
 await route('clientMessages');assert.equal(realtime.removed,true);realtime.callback({new:{...rt,id:'stale-channel',body:'Ne doit jamais apparaître'}});await click('#clientMessages [data-quote]');assert.doesNotMatch(w.document.getElementById('rd-live-chat-messages').textContent,/Ne doit jamais apparaître/);noError();
 await route('quoteDetail');await click('[data-progress="completed"]');assert.equal(tables.rd_projects[0].status,'completed');noError();
 await switchUser('plumber');await route('contractorQuotes');await click('[data-quote-tab="completed"]');assert.match(w.document.querySelector('#contractorQuotes').textContent,/Remplacement robinet/);noError();
 await route('profilePreview');noError();assert.match(w.document.querySelector('#profilePreview').textContent,/Nos réalisations/);await click('[data-business-edit="1"]');fill('rd-business-tagline','Des travaux soignés.');fill('rd-business-bio','Une équipe passionnée et attentive à chaque détail.');fill('rd-business-years','12');w.document.getElementById('rd-business-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(tables.rd_business_pages[0].experience_years,12);assert.match(w.document.querySelector('#profilePreview').textContent,/Des travaux soignés/);
 tables.rd_portfolio.push({id:'portfolio-test',contractor_id:users.plumber.id,title:'Cuisine rénovée',city:'Laval',description:'Une belle réalisation',after_path:'plumber/fixture.jpg'});await route('contractorFeed');await route('profilePreview');noError();assert.match(w.document.querySelector('#profilePreview').textContent,/Cuisine rénovée/);await click('[data-portfolio-edit="portfolio-test"]');fill('rd-portfolio-title','Cuisine transformée');w.document.getElementById('rd-portfolio-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(tables.rd_portfolio[0].title,'Cuisine transformée');await switchUser('client');await route('quoteDetail');await click('[data-business]');noError();assert.match(w.document.querySelector('#businessProfile').textContent,/Cuisine transformée/);assert.equal(w.document.querySelector('#businessProfile [data-business-edit]'),null);await switchUser('plumber');await route('contractorFeed');
 // Uploaded cover/logo and before/after images persist as private paths, not data URLs.
 await route('profilePreview');assert.equal(w.document.querySelector('#profilePreview .rd-business-cover-edit'),null);await click('#profilePreview [data-business-edit="1"]');assert.equal(w.document.querySelector('#profilePreview .rd-business-cover-edit span').textContent,'Modifier la couverture');assert.equal(w.document.getElementById('rd-business-cover').form.id,'rd-business-form');fill('rd-business-bio','Texte conservé pendant le choix de photo.');choosePhoto('rd-business-cover');w.document.getElementById('rd-business-cover').dispatchEvent(new w.Event('change',{bubbles:true}));await pause();assert.equal(w.document.getElementById('rd-business-bio').value,'Texte conservé pendant le choix de photo.');assert.equal(w.document.querySelector('#profilePreview .rd-business-cover img').getAttribute('src'),'blob:test');fill('rd-cover-zoom','2');assert.equal(w.document.querySelector('#profilePreview .rd-business-cover img').style.width,'720px');const cropImage=w.document.querySelector('#profilePreview .rd-business-cover img');for(const [type,x,y] of [['pointerdown',0,0],['pointermove',500,500],['pointerup',500,500]])cropImage.dispatchEvent(Object.assign(new w.Event(type,{bubbles:true,cancelable:true}),{pointerId:7,button:0,clientX:x,clientY:y}));assert.equal(cropImage.style.left,'0px');assert.equal(cropImage.style.top,'0px');choosePhoto('rd-business-logo');w.document.getElementById('rd-business-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(businessUploads.length,2);const cropped=drawCalls.find(x=>x.length===9);assert.ok(cropped,'Cover is saved as a cropped image');assert.equal(cropped[1],0);assert.equal(cropped[2],0);assert.equal(cropped[3],300);assert.equal(cropped[7],1600);assert.match(tables.rd_business_pages[0].cover_path,/^plumber\//);assert.equal(w.document.querySelectorAll('#profilePreview .rd-business-cover img').length,1);
 await click('[data-business-edit="1"]');fill('rd-portfolio-title','Salle de bain');choosePhoto('rd-portfolio-before');choosePhoto('rd-portfolio-after');w.document.getElementById('rd-portfolio-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(businessUploads.length,4);assert.equal(tables.rd_portfolio.length,2);assert.match(tables.rd_portfolio[1].before_path,/^plumber\//);assert.match(tables.rd_portfolio[1].after_path,/^plumber\//);assert.ok(businessUploads.every(x=>x.type==='image/jpeg'));
 // The header saves presentation and pending portfolio changes together, with validation before writes.
 await click('#profilePreview [data-business-edit="1"]');assert.equal(w.document.querySelector('#profilePreview [data-business-save]').textContent,'Sauvegarder les changements');const previousTagline=tables.rd_business_pages[0].tagline;fill('rd-business-tagline','Toutes les modifications enregistrées');fill('rd-portfolio-title','Projet complet');await click('#profilePreview [data-business-save]');assert.equal(tables.rd_business_pages[0].tagline,previousTagline);assert.ok(w.document.querySelector('.rd-live-error'));choosePhoto('rd-portfolio-after');w.document.querySelector('#profilePreview [data-business-save]').click();w.document.querySelector('#profilePreview [data-business-save]').click();await pause();noError();assert.equal(tables.rd_business_pages[0].tagline,'Toutes les modifications enregistrées');assert.equal(tables.rd_portfolio.length,3);assert.equal(tables.rd_portfolio[2].title,'Projet complet');assert.equal(w.document.querySelector('#profilePreview [data-business-save]'),null);assert.equal(w.document.querySelector('#profilePreview .rd-business-cover-edit'),null);
 // Non-retained offers remain non-retained after the winning contractor finishes.
 tables.rd_quotes.push({id:'declined-test',project_id:tables.rd_projects[0].id,contractor_id:users.general.id,status:'declined',amount:900,duration:'2 jours',start_date:'2026-11-15',message:'Autre offre'});
 await switchUser('general');await route('contractorQuotes');await click('[data-quote-tab="completed"]');assert.equal(w.document.querySelector('[data-quote="declined-test"]'),null);await click('[data-quote-tab="declined"]');assert.match(w.document.querySelector('[data-quote="declined-test"]').textContent,/Non retenue/);
 await switchUser('client');await route('contractorFeed');assert.equal(w.location.hash,'#clientDashboard');
 for(const id of ['pro2','services','territory','profilePreview']){await route(id);assert.equal(w.location.hash,'#clientDashboard','Client cannot enter contractor editor: '+id);}
 // A delayed response to project A cannot overwrite the current selection of project B.
 const a={...tables.rd_projects[0],id:'race-a',title:'Projet A',status:'open'},b={...a,id:'race-b',title:'Projet B'};tables.rd_projects.push(a,b);
 await route('clientProjects');let release;const gate=new Promise(r=>release=r);let delayed=false;
 queryDelay=q=>{if(!delayed&&q.table==='rd_projects'&&q.one){delayed=true;return gate;}};
 w.document.querySelector('[data-project="race-a"]').click();await pause();await route('clientProjects');await click('[data-project="race-b"]');release();queryDelay=null;await pause();assert.match(w.document.getElementById('clientProjectDetail').textContent,/Projet B/);await click('[data-progress="archived"]');assert.equal(b.status,'archived');assert.equal(a.status,'open');noError();
 // Delayed message polling never paints a different conversation; drafts stay isolated.
 tables.rd_quotes.push({id:'chat-b',project_id:b.id,contractor_id:users.general.id,status:'pending',amount:123,duration:'1 jour',start_date:'2026-11-15',message:'Nouvelle offre'});tables.rd_messages.push({id:'message-b',quote_id:'chat-b',sender_id:users.general.id,body:'Conversation B uniquement',created_at:new Date().toISOString()});
 await route('clientMessages');await click('[data-quote="'+tables.rd_quotes[0].id+'"]');fill('rd-live-message','Brouillon A');let releaseMessages;const messagesGate=new Promise(r=>releaseMessages=r);let delayedMessages=false;queryDelay=q=>{if(!delayedMessages&&q.table==='rd_messages'){delayedMessages=true;return messagesGate;}};intervals.find(x=>x.ms===15000).fn();await pause();await route('clientMessages');await click('[data-quote="chat-b"]');assert.equal(w.document.getElementById('rd-live-message').value,'');releaseMessages();queryDelay=null;await pause();assert.match(w.document.getElementById('rd-live-chat-messages').textContent,/Conversation B uniquement/);assert.doesNotMatch(w.document.getElementById('rd-live-chat-messages').textContent,/Bonjour/);await route('clientMessages');await click('[data-quote="'+tables.rd_quotes[0].id+'"]');assert.equal(w.document.getElementById('rd-live-message').value,'Brouillon A');
 // Storage denial must never turn a successful server action into an apparent failure.
 const storageProto=Object.getPrototypeOf(w.localStorage),originalSet=storageProto.setItem,originalGet=storageProto.getItem;storageProto.setItem=storageProto.getItem=()=>{throw Error('Storage denied');};await route('clientProjects');await click('[data-project="race-a"]');noError();assert.match(w.document.getElementById('clientProjectDetail').textContent,/Projet A/);storageProto.setItem=originalSet;storageProto.getItem=originalGet;
 // Offline read errors offer a working retry instead of leaving a broken empty page.
 await route('clientMessages');let fail=true;queryDelay=q=>{if(fail&&q.table==='rd_projects'){fail=false;throw Error('Failed to fetch');}};await route('clientProjects');assert.match(w.document.querySelector('#clientProjects .rd-live-error').textContent,/connexion Internet/);queryDelay=null;await click('#clientProjects [data-refresh]');noError();assert.match(w.document.getElementById('clientProjects').textContent,/Projet A/);
 // An unchanged background refresh preserves the selected card and focus.
 await route('clientProjects');const stable=w.document.querySelector('[data-project="race-a"]');stable.focus();await click('[data-project-tab="active"]');assert.equal(w.document.querySelector('[data-project="race-a"]'),stable);
 // User-controlled content must remain literal text, even when it resembles HTML.
 a.title='<img src=x onerror="alert(1)">';a.description='<script>alert(1)</script> Description de test.';await click('#clientProjects [data-project="race-a"]');assert.equal(w.document.querySelector('#clientProjectDetail img[src="x"]'),null);assert.equal(w.document.querySelector('#clientProjectDetail script'),null);assert.match(w.document.getElementById('clientProjectDetail').textContent,/<img src=x/);a.title='Projet A';
 // A logout failure must keep the app aligned with the still-active session.
 await switchUser('plumber');await route('contractorFeed');const signOut=db.auth.signOut;db.auth.signOut=async()=>({error:{message:'Failed to fetch'}});await click('#contractorFeed [data-logout]');assert.equal(current.id,'plumber');assert.equal(w.location.hash,'#contractorFeed');assert.match(w.document.querySelector('.rd-live-error').textContent,/connexion Internet/);db.auth.signOut=signOut;await route('contractorQuotes');await route('contractorFeed');noError();await switchUser('client');
 // Startup redirect must update CSS :target as well as the URL after the intro.
 const originalReplaceState=w.history.replaceState;w.history.replaceState=()=>{throw Error('replaceState does not update the CSS target');};await route('home');assert.equal(w.location.hash,'#clientDashboard');w.history.replaceState=originalReplaceState;
 // Signed-in navigation cannot return to the public entry flow, including native history back.
 for(const id of ['accueil','home','intro','client','pro1','loginClient','loginPro','clientHome','doneClient','page-inconnue']){await route(id);assert.equal(w.location.hash,'#clientDashboard',id);}
 await route('clientProjects');w.history.back();await pause();assert.equal(w.location.hash,'#clientDashboard');
 await switchUser('plumber');for(const id of ['accueil','home','client','pro1','loginPro']){await route(id);assert.equal(w.location.hash,'#contractorFeed',id);}
 await route('profilePreview');assert.equal(w.document.querySelector('#profilePreview a.back').getAttribute('href'),'#contractorFeed');await click('#profilePreview a.back');assert.equal(w.location.hash,'#contractorFeed');
 // A signed attachment URL that resolves late cannot repaint a new conversation.
 await switchUser('client');const qa=tables.rd_quotes[0].id;tables.rd_messages.push({id:'slow-photo',quote_id:qa,sender_id:'plumber',body:'Pièce jointe A',attachment_path:'client/attachment-a.jpg',attachment_type:'image/jpeg',created_at:new Date().toISOString()});await route('clientMessages');await click('[data-quote="'+qa+'"]');
 const storageFrom=db.storage.from;let releaseSigned,holdSigned=true;const signedGate=new Promise(r=>releaseSigned=r);db.storage.from=bucket=>({...storageFrom(bucket),createSignedUrl:async path=>{if(holdSigned&&path==='client/attachment-a.jpg'){holdSigned=false;await signedGate;}return storageFrom(bucket).createSignedUrl(path);}});intervals.find(x=>x.ms===15000).fn();await pause();await route('clientMessages');await click('[data-quote="chat-b"]');releaseSigned();await pause();assert.doesNotMatch(w.document.getElementById('rd-live-chat-messages').textContent,/Pièce jointe A/);assert.match(w.document.getElementById('rd-live-chat-messages').textContent,/Conversation B uniquement/);db.storage.from=storageFrom;await switchUser('plumber');
 // On a slow connection the transition snapshot must wait for actual destination data.
 if(motionBoot){await route('clientProjects');let releaseSlow;const slowGate=new Promise(r=>releaseSlow=r);let slowRead=true;queryDelay=q=>{if(slowRead&&q.table==='rd_projects'&&q.one){slowRead=false;return slowGate;}};const snapshotCount=transitionSnapshots.length;w.document.querySelector('[data-project="race-a"]').click();await new Promise(r=>setTimeout(r,280));assert.equal(transitionSnapshots.length,snapshotCount);releaseSlow();queryDelay=null;await pause();assert.match(transitionSnapshots.at(-1).text,/Projet A/);assert.doesNotMatch(transitionSnapshots.at(-1).text,/Chargement/);}
 // Returning to contractor lists retains position and content while the network is slow.
 await route('contractorFeed');const feed=w.document.getElementById('contractorFeed');feed.scrollTop=240;feed.dispatchEvent(new w.Event('scroll'));await click('#contractorFeed [data-project="race-a"]');
 let releaseFeed;const feedGate=new Promise(r=>releaseFeed=r);queryDelay=q=>q.table==='rd_projects'&&!q.one?feedGate:null;await route('contractorFeed');assert.equal(feed.scrollTop,240);assert.match(feed.textContent,/Projet A/);assert.doesNotMatch(feed.textContent,/Chargement/);releaseFeed();queryDelay=null;await pause();assert.equal(feed.scrollTop,240);
 // A new project during polling preserves focus and scroll instead of jumping the list.
 const focusedCard=feed.querySelector('[data-project="race-a"]');focusedCard.focus();tables.rd_projects.push({...a,id:'refresh-new',title:'Nouveau projet'});intervals.find(x=>x.ms===15000).fn();await pause();assert.equal(w.document.activeElement.getAttribute('data-project'),'race-a');assert.equal(feed.scrollTop,240);assert.match(feed.textContent,/Nouveau projet/);
 // Slow polling stays single-flight: repeated ticks cannot invalidate the pending response.
 let releasePoll,pollReads=0;const pollGate=new Promise(r=>releasePoll=r);queryDelay=q=>{if(q.table==='rd_projects'&&!q.one){pollReads++;return pollGate;}};tables.rd_projects.push({...a,id:'slow-poll-new',title:'Projet après réseau lent'});const poll=intervals.find(x=>x.ms===15000).fn;poll();await pause();poll();w.dispatchEvent(new w.Event('focus'));await pause();assert.equal(pollReads,1);releasePoll();queryDelay=null;await pause();assert.match(feed.textContent,/Projet après réseau lent/);noError();
 await switchUser('general');await route('contractorFeed');assert.equal(feed.scrollTop,0,'List position is isolated between accounts');await switchUser('plumber');
 // Radius choices must override the previously saved custom value.
 await route('territory');assert.equal(w.document.getElementById('rd-territory-field-2').value,'50');
 w.document.getElementById('r25').checked=true;w.document.getElementById('r25').dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(w.document.getElementById('rd-territory-field-2').value,'');
 await click('#territory a.primary');assert.equal(tables.rd_profiles.find(p=>p.id==='plumber').radius_km,25);noError();
 // Client avatar button opens the profile and a city edit updates coordinates too.
 await switchUser('client');await route('clientDashboard');await click('#clientDashboard [data-account]');assert.equal(w.location.hash,'#clientProfile');await click('[data-client-profile-edit]');
 fill('pj-client-city','Ville inventée');w.document.getElementById('pj-client-profile-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();assert.match(w.document.querySelector('.rd-live-error').textContent,/ville dans les suggestions/);
 fill('pj-client-city','Terrebonne');w.document.getElementById('pj-client-profile-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();const clientProfile=tables.rd_profiles.find(p=>p.id==='client'),terrebonne=JSON.parse(fs.readFileSync(path.join(__dirname,'../app/cities.json'))).find(c=>c[0]==='Terrebonne');assert.equal(clientProfile.city,'Terrebonne');assert.equal(clientProfile.latitude,terrebonne[1]);assert.equal(clientProfile.longitude,terrebonne[2]);
 // File-only messages pass native form validity and never leak to another conversation.
 await route('clientMessages');await click('[data-quote="'+tables.rd_quotes[0].id+'"]');fill('rd-live-message','');choosePhoto('rd-chat-file');w.document.getElementById('rd-chat-file').dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(w.document.getElementById('rd-live-chat-form').checkValidity(),true);assert.ok(w.document.getElementById('rd-chat-file-preview'));
 await route('clientMessages');await click('[data-quote="chat-b"]');assert.equal(w.document.getElementById('rd-chat-file-preview'),null);
 choosePhoto('rd-chat-file');w.document.getElementById('rd-chat-file').dispatchEvent(new w.Event('change',{bubbles:true}));const beforeMessages=tables.rd_messages.length;w.document.getElementById('rd-live-chat-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(tables.rd_messages.length,beforeMessages+1);assert.equal(tables.rd_messages.at(-1).body,'');assert.equal(tables.rd_messages.at(-1).quote_id,'chat-b');assert.match(tables.rd_messages.at(-1).attachment_path,/client\/chat-b\//);
 // Direct completion works without the intermediate work-start click.
 const direct={...a,id:'direct-complete',status:'accepted',accepted_quote_id:'direct-quote'};tables.rd_projects.push(direct);tables.rd_quotes.push({id:'direct-quote',project_id:direct.id,contractor_id:'plumber',status:'accepted',amount:250});await route('clientProjects');await click('[data-project="direct-complete"]');await click('[data-progress="completed"]');assert.equal(direct.status,'completed');noError();
 await switchUser('plumber');await route('profilePreview');
 fill('rd-pro1-field-1','Ancien prénom privé');fill('rd-pro2-field-3','514-555-1234');await route('profilePreview');
 await route('contractorFeed');await click('#contractorFeed [data-logout]');assert.equal(current,null);assert.equal(w.location.hash,'#accueil');assert.equal(w.document.getElementById('rd-pro1-field-1').value,'');assert.equal(w.document.getElementById('rd-pro2-field-3').value,'');assert.equal(w.document.getElementById('profilePreview').textContent,'');assert.doesNotMatch(w.document.getElementById('clientChat').textContent,/Bonjour/);await route('client');assert.equal(w.location.hash,'#client');
 console.log('PASS:  publish → trade-filtered feed → quote → acceptance → work progress → shared messages → completed lists; repeated profile, session refresh, bid/chat drafts, declined history, role guard, delayed selection, storage denial and stable refresh');dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
