const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require(process.env.RD_JSDOM_PATH||'jsdom');
const core=require('../app/core.js');
const users={client:{id:'client',email:'client@example.invalid'},plumber:{id:'plumber',email:'plumber@example.invalid'},electrician:{id:'electrician',email:'electrician@example.invalid'},general:{id:'general',email:'general@example.invalid'}};
const tables={rd_profiles:Object.entries(users).map(([k,v])=>({id:v.id,role:k==='client'?'client':'contractor',display_name:k,company_name:k==='client'?'':k,city:'Laval',latitude:45.56995,longitude:-73.692,services:k==='client'?[]:[k==='plumber'?'plumbing':k==='electrician'?'electrical':'general'],radius_km:50,rbq:''})),rd_projects:[],rd_quotes:[],rd_messages:[],rd_project_photos:[],rd_account_details:[]};
tables.rd_business_pages=[];tables.rd_portfolio=[];
let current=users.client,authCallback,queryDelay=null;const intervals=[];
const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),{url:'https://renodirect.vercel.app/#clientDashboard',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
w.HTMLElement.prototype.scrollIntoView=function(){};w.confirm=()=>true;w.fetch=async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(__dirname,'../app/cities.json')))});w.setInterval=(fn,ms)=>{intervals.push({fn,ms});return intervals.length;};
class Query {
 upsert(row){this.mode='upsert';this.row=row;return this;}
 constructor(table){this.table=table;this.filters=[];this.mode='select';this.one=false;}
 select(){return this;}eq(k,v){this.filters.push(r=>r[k]===v);return this;}in(k,vs){this.filters.push(r=>vs.includes(r[k]));return this;}order(){return this;}limit(n){this.max=n;return this;}maybeSingle(){this.one=true;return this;}single(){this.one=true;return this;}insert(rows){this.mode='insert';this.rows=Array.isArray(rows)?rows:[rows];return this;}update(row){this.mode='update';this.row=row;return this;}
 then(resolve,reject){return Promise.resolve().then(async()=>{
 let rows=tables[this.table];if(this.mode==='upsert'){let row=rows.find(x=>x.id===this.row.id);if(row)Object.assign(row,this.row);else{row={...this.row};rows.push(row);}rows=[row];}else if(this.mode==='insert'){rows=this.rows.map(r=>({...r,id:r.id||w.crypto.randomUUID(),created_at:new Date().toISOString(),...(!r.status&&['rd_projects','rd_quotes'].includes(this.table)?{status:this.table==='rd_projects'?'open':'pending'}:{})}));tables[this.table].push(...rows);}else if(this.mode==='update'){rows=rows.filter(r=>this.filters.every(f=>f(r)));rows.forEach(r=>Object.assign(r,this.row));}
 if(this.mode==='select'){if(this.table==='rd_projects'){const p=tables.rd_profiles.find(p=>p.id===current?.id);rows=rows.filter(r=>r.client_id===current?.id||core.matches(p,r)||tables.rd_quotes.some(q=>q.project_id===r.id&&q.contractor_id===current?.id));}else if(this.table==='rd_quotes')rows=rows.filter(q=>q.contractor_id===current?.id||tables.rd_projects.some(p=>p.id===q.project_id&&p.client_id===current?.id));rows=rows.filter(r=>this.filters.every(f=>f(r)));}
 if(this.max)rows=rows.slice(0,this.max);if(queryDelay)await queryDelay(this);return {data:this.one?(rows[0]||null):rows,error:null};
 }).then(resolve,reject);}
}
const db={from:t=>new Query(t),auth:{getSession:async()=>({data:{session:{user:current}},error:null}),onAuthStateChange:fn=>{authCallback=fn;return {data:{subscription:{unsubscribe(){}}}};},signOut:async()=>{current=null;authCallback('SIGNED_OUT',null);return {error:null};}},storage:{from:()=>({createSignedUrls:async()=>({data:[]})})},rpc:async(name,args)=>{if(name==='rd_accept_quote'){const q=tables.rd_quotes.find(q=>q.id===args.quote),p=tables.rd_projects.find(p=>p.id===q.project_id);assert.equal(p.client_id,current.id);assert.equal(p.status,'open');tables.rd_quotes.filter(x=>x.project_id===p.id).forEach(x=>x.status=x.id===q.id?'accepted':'declined');p.status='accepted';p.accepted_quote_id=q.id;return {data:p.id};}const p=tables.rd_projects.find(p=>p.id===args.project);p.status=args.next_status;return {data:null};}};
w.supabase={createClient:()=>db};w.eval(fs.readFileSync(path.join(__dirname,'../app/core.js'),'utf8'));w.eval(fs.readFileSync(path.join(__dirname,'../app/marketplace.js'),'utf8'));
const pause=()=>new Promise(r=>setTimeout(r,35));async function route(id){w.location.hash=id;await pause();}
function fill(id,v){const el=w.document.getElementById(id);el.value=v;el.dispatchEvent(new w.Event('input',{bubbles:true}));}async function click(selector){const e=w.document.querySelector(selector);assert.ok(e,selector);e.click();await pause();}
async function switchUser(key){current=users[key];authCallback('SIGNED_IN',{user:current});await pause();}
function noError(){assert.equal(w.document.querySelector('.rd-live-error'),null,w.document.querySelector('.rd-live-error')?.textContent);}
const businessUploads=[],drawCalls=[];w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.Image=class{constructor(){this.width=600;this.height=400;}async decode(){}};w.HTMLCanvasElement.prototype.getContext=()=>({drawImage(...args){drawCalls.push(args);}});w.HTMLCanvasElement.prototype.toBlob=function(fn){fn(new w.Blob(['fixture'],{type:'image/jpeg'}));};
db.storage.from=()=>({upload:async(path,blob)=>{businessUploads.push({path,type:blob.type});return {data:{path},error:null};},createSignedUrls:async paths=>({data:paths.map(path=>({path,signedUrl:'https://example.invalid/'+path}))})});
function choosePhoto(id){Object.defineProperty(w.document.getElementById(id),'files',{configurable:true,value:[new w.File(['fixture'],'fixture.png',{type:'image/png'})]});}
(async()=>{
 await pause();assert.match(w.document.querySelector('#clientDashboard').textContent,/Aucun projet publié/);await click('#clientDashboard a[href="#newProject"]');await click('[data-service="plumbing"]');fill('rd80ProjectName','Remplacement robinet');fill('rd62Description','Remplacer le robinet de la cuisine et vérifier les tuyaux.');await click('#projectDetails .rd52-next');await click('#rd62BudgetOptions a');await click('#rd62TimingOptions a');fill('rd62City','Laval');fill('rd62Postal','H7X 0A0');await click('#projectLocation .rd52-next');assert.match(w.document.querySelector('#rd-live-review').textContent,/Remplacement robinet/);w.document.getElementById('rd72Publish').click();w.document.getElementById('rd72Publish').click();await pause();noError();assert.equal(tables.rd_projects.length,1);assert.match(w.document.querySelector('#clientProjectDetail').textContent,/Aucune soumission/);
 const incomingId=w.crypto.randomUUID();tables.rd_quotes.push({id:incomingId,project_id:tables.rd_projects[0].id,contractor_id:users.plumber.id,amount:325,status:'pending',created_at:new Date().toISOString()});w.dispatchEvent(new w.Event('focus'));await pause();assert.match(w.document.getElementById('rd-quote-notice').textContent,/325/);await click('[data-dismiss-quotes]');assert.equal(w.document.getElementById('rd-quote-notice'),null);w.dispatchEvent(new w.Event('focus'));await pause();assert.equal(w.document.getElementById('rd-quote-notice'),null);tables.rd_quotes.splice(tables.rd_quotes.findIndex(q=>q.id===incomingId),1);

 await switchUser('electrician');await route('contractorFeed');assert.match(w.document.querySelector('#rd62LiveProjects').textContent,/Aucun projet correspondant/);
 await switchUser('general');await route('contractorFeed');assert.equal(w.document.querySelectorAll('#rd62LiveProjects [data-project]').length,1);
 await switchUser('plumber');await route('contractorFeed');assert.equal(w.document.getElementById('rd87MatchCount').textContent,'1');await click('#rd62LiveProjects [data-project]');await click('#contractorProject a[href="#contractorBid"]');fill('rd-bid-amount','475');fill('rd-bid-duration','1 journée');fill('rd-bid-date','2026-11-15');fill('rd-bid-message','Installation du robinet, matériel et déplacement inclus.');await route('contractorProject');await route('contractorBid');assert.equal(w.document.getElementById('rd-bid-amount').value,'475');assert.match(w.document.getElementById('rd-bid-message').value,/Installation/);authCallback('TOKEN_REFRESHED',{user:current});await pause();assert.equal(w.document.getElementById('rd-bid-amount').value,'475');w.document.getElementById('rd-live-bid').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(tables.rd_quotes.length,1);await route('contractorQuotes');assert.match(w.document.querySelector('#contractorQuotes').textContent,/475/);
 await switchUser('client');assert.match(w.document.getElementById('rd-quote-notice').textContent,/Nouvelle soumission reçue/);assert.match(w.document.getElementById('rd-quote-notice').textContent,/475/);await route('clientProjects');await click('#clientProjects [data-project]');assert.match(w.document.querySelector('#clientProjectDetail').textContent,/Soumissions reçues \(1\)/);await click('#clientProjectDetail [data-quote]');assert.equal(w.document.getElementById('rd-quote-notice'),null);await switchUser('plumber');assert.equal(w.document.getElementById('rd-quote-notice'),null);await switchUser('client');assert.equal(w.document.getElementById('rd-quote-notice'),null);await click('[data-accept]');noError();assert.equal(tables.rd_projects[0].status,'accepted');assert.match(w.document.querySelector('#quoteAccepted').textContent,/Entrepreneur choisi/);
 await route('quoteDetail');await click('[data-progress="in_progress"]');assert.equal(tables.rd_projects[0].status,'in_progress');await click('#quoteDetail a[href="#clientChat"]');fill('rd-live-message','Bonjour, à quelle heure êtes-vous disponible ?');const typed=w.document.getElementById('rd-live-message');typed.focus();authCallback('TOKEN_REFRESHED',{user:current});await pause();assert.equal(w.document.getElementById('rd-live-message'),typed);assert.equal(w.document.activeElement,typed);await route('clientMessages');await click('#clientMessages [data-quote]');assert.equal(w.document.getElementById('rd-live-message').value,'Bonjour, à quelle heure êtes-vous disponible ?');w.document.getElementById('rd-live-chat-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();assert.equal(tables.rd_messages.length,1);assert.match(w.document.querySelector('#rd-live-chat-messages').textContent,/Bonjour/);
 await route('quoteDetail');await click('[data-progress="completed"]');assert.equal(tables.rd_projects[0].status,'completed');noError();
 await switchUser('plumber');await route('contractorQuotes');await click('[data-quote-tab="completed"]');assert.match(w.document.querySelector('#contractorQuotes').textContent,/Remplacement robinet/);noError();
 await route('profilePreview');noError();assert.match(w.document.querySelector('#profilePreview').textContent,/Nos réalisations/);await click('[data-business-edit="1"]');fill('rd-business-tagline','Des travaux soignés.');fill('rd-business-bio','Une équipe passionnée et attentive à chaque détail.');fill('rd-business-years','12');w.document.getElementById('rd-business-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(tables.rd_business_pages[0].experience_years,12);assert.match(w.document.querySelector('#profilePreview').textContent,/Des travaux soignés/);
 tables.rd_portfolio.push({id:'portfolio-test',contractor_id:users.plumber.id,title:'Cuisine rénovée',city:'Laval',description:'Une belle réalisation',after_path:'plumber/fixture.jpg'});await route('contractorFeed');await route('profilePreview');noError();assert.match(w.document.querySelector('#profilePreview').textContent,/Cuisine rénovée/);await click('[data-portfolio-edit="portfolio-test"]');fill('rd-portfolio-title','Cuisine transformée');w.document.getElementById('rd-portfolio-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(tables.rd_portfolio[0].title,'Cuisine transformée');await switchUser('client');await route('quoteDetail');await click('[data-business]');noError();assert.match(w.document.querySelector('#businessProfile').textContent,/Cuisine transformée/);assert.equal(w.document.querySelector('#businessProfile [data-business-edit]'),null);await switchUser('plumber');await route('contractorFeed');
 // Uploaded cover/logo and before/after images persist as private paths, not data URLs.
 await route('profilePreview');assert.equal(w.document.querySelector('#profilePreview .rd-business-cover-edit'),null);await click('#profilePreview [data-business-edit="1"]');assert.equal(w.document.querySelector('#profilePreview .rd-business-cover-edit span').textContent,'Modifier la couverture');assert.equal(w.document.getElementById('rd-business-cover').form.id,'rd-business-form');fill('rd-business-bio','Texte conservé pendant le choix de photo.');choosePhoto('rd-business-cover');w.document.getElementById('rd-business-cover').dispatchEvent(new w.Event('change',{bubbles:true}));await pause();assert.equal(w.document.getElementById('rd-business-bio').value,'Texte conservé pendant le choix de photo.');assert.equal(w.document.querySelector('#profilePreview .rd-business-cover img').getAttribute('src'),'blob:test');fill('rd-cover-zoom','2');assert.equal(w.document.querySelector('#profilePreview .rd-business-cover img').style.width,'720px');const cropImage=w.document.querySelector('#profilePreview .rd-business-cover img');for(const [type,x,y] of [['pointerdown',0,0],['pointermove',500,500],['pointerup',500,500]])cropImage.dispatchEvent(Object.assign(new w.Event(type,{bubbles:true,cancelable:true}),{pointerId:7,button:0,clientX:x,clientY:y}));assert.equal(cropImage.style.left,'0px');assert.equal(cropImage.style.top,'0px');choosePhoto('rd-business-logo');w.document.getElementById('rd-business-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(businessUploads.length,2);const cropped=drawCalls.find(x=>x.length===9);assert.ok(cropped,'Cover is saved as a cropped image');assert.equal(cropped[1],0);assert.equal(cropped[2],0);assert.equal(cropped[3],300);assert.equal(cropped[7],1600);assert.match(tables.rd_business_pages[0].cover_path,/^plumber\//);assert.equal(w.document.querySelectorAll('#profilePreview .rd-business-cover img').length,1);
 await click('[data-business-edit="1"]');fill('rd-portfolio-title','Salle de bain');choosePhoto('rd-portfolio-before');choosePhoto('rd-portfolio-after');w.document.getElementById('rd-portfolio-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();noError();assert.equal(businessUploads.length,4);assert.equal(tables.rd_portfolio.length,2);assert.match(tables.rd_portfolio[1].before_path,/^plumber\//);assert.match(tables.rd_portfolio[1].after_path,/^plumber\//);assert.ok(businessUploads.every(x=>x.type==='image/jpeg'));
 // Non-retained offers remain non-retained after the winning contractor finishes.
 tables.rd_quotes.push({id:'declined-test',project_id:tables.rd_projects[0].id,contractor_id:users.general.id,status:'declined',amount:900,duration:'2 jours',start_date:'2026-11-15',message:'Autre offre'});
 await switchUser('general');await route('contractorQuotes');await click('[data-quote-tab="completed"]');assert.equal(w.document.querySelector('[data-quote="declined-test"]'),null);await click('[data-quote-tab="declined"]');assert.match(w.document.querySelector('[data-quote="declined-test"]').textContent,/Non retenue/);
 await switchUser('client');await route('contractorFeed');assert.equal(w.location.hash,'#clientDashboard');
 // A delayed response to project A cannot overwrite the current selection of project B.
 const a={...tables.rd_projects[0],id:'race-a',title:'Projet A',status:'open'},b={...a,id:'race-b',title:'Projet B'};tables.rd_projects.push(a,b);
 await route('clientProjects');let release;const gate=new Promise(r=>release=r);let delayed=false;
 queryDelay=q=>{if(!delayed&&q.table==='rd_projects'&&q.one){delayed=true;return gate;}};
 w.document.querySelector('[data-project="race-a"]').click();await pause();await route('clientProjects');await click('[data-project="race-b"]');release();queryDelay=null;await pause();assert.match(w.document.getElementById('clientProjectDetail').textContent,/Projet B/);await click('[data-progress="archived"]');assert.equal(b.status,'archived');assert.equal(a.status,'open');noError();
 // Delayed message polling never paints a different conversation; drafts stay isolated.
 tables.rd_quotes.push({id:'chat-b',project_id:b.id,contractor_id:users.general.id,status:'pending',amount:123,duration:'1 jour',start_date:'2026-11-15',message:'Nouvelle offre'});tables.rd_messages.push({id:'message-b',quote_id:'chat-b',sender_id:users.general.id,body:'Conversation B uniquement',created_at:new Date().toISOString()});
 await route('clientMessages');await click('[data-quote="'+tables.rd_quotes[0].id+'"]');fill('rd-live-message','Brouillon A');let releaseMessages;const messagesGate=new Promise(r=>releaseMessages=r);let delayedMessages=false;queryDelay=q=>{if(!delayedMessages&&q.table==='rd_messages'){delayedMessages=true;return messagesGate;}};intervals.find(x=>x.ms===15000).fn();await pause();await route('clientMessages');await click('[data-quote="chat-b"]');assert.equal(w.document.getElementById('rd-live-message').value,'');releaseMessages();queryDelay=null;await pause();assert.match(w.document.getElementById('rd-live-chat-messages').textContent,/Conversation B uniquement/);assert.doesNotMatch(w.document.getElementById('rd-live-chat-messages').textContent,/Bonjour/);await route('clientMessages');await click('[data-quote="'+tables.rd_quotes[0].id+'"]');assert.equal(w.document.getElementById('rd-live-message').value,'Brouillon A');
 // Storage denial must never turn a successful server action into an apparent failure.
 const storageProto=Object.getPrototypeOf(w.localStorage),originalSet=storageProto.setItem,originalGet=storageProto.getItem;storageProto.setItem=storageProto.getItem=()=>{throw Error('Storage denied');};await route('clientProjects');await click('[data-project="race-a"]');noError();assert.match(w.document.getElementById('clientProjectDetail').textContent,/Projet A/);storageProto.setItem=originalSet;storageProto.getItem=originalGet;
 // Offline read errors offer a working retry instead of leaving a broken empty page.
 await route('clientMessages');let fail=true;queryDelay=q=>{if(fail&&q.table==='rd_projects'){fail=false;throw Error('Failed to fetch');}};await route('clientProjects');assert.match(w.document.querySelector('#clientProjects .rd-live-error').textContent,/connexion Internet/);queryDelay=null;await click('#clientProjects [data-refresh]');noError();assert.match(w.document.getElementById('clientProjects').textContent,/Projet A/);
 // An unchanged background refresh preserves the selected card and focus.
 await route('clientProjects');const stable=w.document.querySelector('[data-project="race-a"]');stable.focus();await click('[data-project-tab="active"]');assert.equal(w.document.querySelector('[data-project="race-a"]'),stable);
 // Startup redirect must update CSS :target as well as the URL after the intro.
 const originalReplaceState=w.history.replaceState;w.history.replaceState=()=>{throw Error('replaceState does not update the CSS target');};await route('home');assert.equal(w.location.hash,'#clientDashboard');w.history.replaceState=originalReplaceState;
 // Signed-in navigation cannot return to the public entry flow, including native history back.
 for(const id of ['accueil','home','intro','client','pro1','loginClient','loginPro']){await route(id);assert.equal(w.location.hash,'#clientDashboard',id);}
 await route('clientProjects');w.history.back();await pause();assert.equal(w.location.hash,'#clientDashboard');
 await switchUser('plumber');for(const id of ['accueil','home','client','pro1','loginPro']){await route(id);assert.equal(w.location.hash,'#contractorFeed',id);}
 await route('profilePreview');assert.equal(w.document.querySelector('#profilePreview a.back').getAttribute('href'),'#contractorFeed');await click('#profilePreview a.back');assert.equal(w.location.hash,'#contractorFeed');
 await click('#contractorFeed [data-logout]');assert.equal(current,null);assert.equal(w.location.hash,'#accueil');await route('client');assert.equal(w.location.hash,'#client');
 console.log('PASS:  publish → trade-filtered feed → quote → acceptance → work progress → shared messages → completed lists; repeated profile, session refresh, bid/chat drafts, declined history, role guard, delayed selection, storage denial and stable refresh');dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
