/* RénoDirect: authenticated marketplace flows. No demo projects or offers. */
(function(){
'use strict';
const db=window.supabase.createClient('https://qefpomgdknlcsavkritc.supabase.co','sb_publishable_qpOjNgQIyWPAwrvh73VSWA_vXIXvqQf');
const {services,inputServices,normalize,serviceKey}=window.RDCore;
const $=s=>document.querySelector(s), byId=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v).toLocaleString('fr-CA',{style:'currency',currency:'CAD'});
const labels={open:'Publié',accepted:'Entrepreneur choisi',in_progress:'Travaux en cours',completed:'Terminé',archived:'Archivé',pending:'En attente',declined:'Non retenue'};
let profileLoading=null;
let user=null,profile=null,accountDetails=null,cities=[],selectedProject=null,selectedQuote=null,routeVersion=0,busy=false,quoteTab='pending',projectTab='active',signupProfile=null;
let draft={service:'',type:'',budget:'',timing:''};
const contractorRoutes=new Set(['contractorFeed','contractorProject','contractorBid','contractorQuotes']);
const clientRoutes=new Set(['clientDashboard','newProject','projectDetails','projectBudget','projectTiming','projectLocation','projectReview','clientProjects','clientProjectsPublished','clientProjectDetail','clientAcceptedProject']);
const sharedRoutes=new Set(['quoteDetail','quoteAccepted','clientMessages','clientChat']);
const editingRoutes=new Set(['pro2','services','territory','building','profilePreview']);
function route(){return location.hash.slice(1).split('?')[0];}
let navigatePage=id=>{location.hash=id;},transitionRouting=false;
const entryRoutes=new Set(['','home','intro','accueil','client','pro1','loginClient','loginPro']);
function signedInRoute(id){return user&&profile&&entryRoutes.has(id)?(profile.role==='contractor'?'contractorFeed':'clientDashboard'):id;}
function go(id){navigatePage(signedInRoute(id));}
function guardSessionRoute(){const id=route(),target=signedInRoute(id);if(target===id)return false;location.replace('#'+target);byId('rd105')?.remove();return true;}
function installPageTransitions(){
 const style=document.createElement('style');style.id='rd-page-motion';
 style.textContent=`.screen:target,.screen:target > .top,.screen:target > .success{animation:none!important}
 ::view-transition-group(root){animation-duration:300ms;animation-timing-function:cubic-bezier(.22,1,.36,1)}
 ::view-transition-old(root){animation:rd-snapshot-out 300ms cubic-bezier(.22,1,.36,1) both;mix-blend-mode:normal}
 ::view-transition-new(root){animation:rd-snapshot-in 300ms cubic-bezier(.22,1,.36,1) both;mix-blend-mode:normal}
 @keyframes rd-snapshot-out{from{opacity:1}to{opacity:0}}
 @keyframes rd-snapshot-in{from{opacity:0}to{opacity:1}}
 @media(prefers-reduced-motion:reduce){::view-transition-group(root),::view-transition-old(root),::view-transition-new(root){animation:none!important}}`;
 document.head.append(style);
 let active=null,serial=0;
 const reduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 const change=async id=>{if(route()===id)return;await new Promise(resolve=>{window.addEventListener('hashchange',resolve,{once:true});location.hash=id;});};
 navigatePage=id=>{
  const ticket=++serial;
  if(active){active.skipTransition?.();active=null;}
  if(route()===id){transitionRouting=false;return;}
  if(reduced()){location.hash=id;return;}
  if(typeof document.startViewTransition==='function'){
   transitionRouting=true;
   const transition=document.startViewTransition(async()=>{
    if(ticket!==serial)return;
    await change(id);
    await transitionRender();
    // Snapshot the rendered destination, keeping the previous page visible while loading.
   });active=transition;
   transition.ready.catch(()=>{});
   transition.finished.catch(()=>{}).finally(()=>{if(ticket===serial){active=null;transitionRouting=false;}});
   transition.updateCallbackDone.catch(()=>{if(ticket===serial){transitionRouting=false;location.hash=id;}});
  }else{
   // Older browsers: finish a short fade-out before changing the visible page.
   const current=byId(route())||byId('rd105');
   const outgoing=current?.animate?.([{opacity:1},{opacity:0}],{duration:130,fill:'forwards',easing:'ease-out'});
   const update=async()=>{if(ticket!==serial){outgoing?.cancel();return;}transitionRouting=true;
    try{await change(id);await transitionRender();}finally{outgoing?.cancel();if(ticket===serial)transitionRouting=false;}
    const incoming=byId(route());incoming?.animate?.([{opacity:0},{opacity:1}],{duration:180,easing:'ease-out'});
   };if(outgoing)outgoing.finished.then(update,()=>{});else void update();
  }
 };
 document.addEventListener('click',e=>{
  if(e.defaultPrevented||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;
  const link=e.target.closest('a[href^="#"]');if(!link||link.hasAttribute('download')||link.target)return;
  const destination=link.getAttribute('href').slice(1);if(!destination||!byId(destination))return;
  e.preventDefault();go(destination);
 });
 document.addEventListener('click',e=>{if(e.target.closest('#rd105,.rd160-back')){const home=!!e.target.closest('.rd160-back');e.preventDefault();e.stopPropagation();go(home?'home':'accueil');}},true);
}

async function transitionRender(){await Promise.race([render(),new Promise(resolve=>setTimeout(resolve,220))]);}
function notify(message){let e=byId('rd-live-notice');if(!e){e=document.createElement('div');e.id='rd-live-notice';e.className='rd-live-notice';e.setAttribute('role','status');document.body.append(e);}e.textContent=message;clearTimeout(notify.timer);notify.timer=setTimeout(()=>e.remove(),6500);}
let quoteNoticeRows=[],quoteNoticeOwner=null,quoteNoticeLoading=false;
function clearQuoteNotice(){byId('rd-quote-notice')?.remove();quoteNoticeRows=[];quoteNoticeOwner=null;}
function readQuoteNoticeIds(id){try{return new Set(JSON.parse(localStorage.getItem('rd-quote-read-'+id)||'[]'));}catch(e){return new Set();}}
function markQuoteNoticeRead(ids){if(!user||profile?.role!=='client')return;const seen=readQuoteNoticeIds(user.id);ids.forEach(id=>seen.add(id));try{localStorage.setItem('rd-quote-read-'+user.id,JSON.stringify([...seen].slice(-2000)));}catch(e){}quoteNoticeRows=quoteNoticeRows.filter(q=>!seen.has(q.id));paintQuoteNotice();}
function paintQuoteNotice(){
 byId('rd-quote-notice')?.remove();if(profile?.role!=='client'||user?.id!==quoteNoticeOwner||!quoteNoticeRows.length)return;
 const q=quoteNoticeRows[0],box=document.createElement('aside');box.id='rd-quote-notice';box.setAttribute('role','status');box.setAttribute('aria-live','polite');
 box.innerHTML='<span class="rd-quote-notice-icon" aria-hidden="true">✦</span><a href="#quoteDetail" data-quote="'+esc(q.id)+'"><strong>'+ (quoteNoticeRows.length>1?quoteNoticeRows.length+' nouvelles soumissions':'Nouvelle soumission reçue')+'</strong><span>'+esc(money(q.amount))+' · '+esc(q.project_title)+'</span><b>Consulter →</b></a><button type="button" data-dismiss-quotes aria-label="Fermer la notification">×</button>';
 document.body.append(box);
}
async function checkQuoteNotifications(){
 if(document.hidden)return;if(!user||profile?.role!=='client'){clearQuoteNotice();return;}if(quoteNoticeLoading)return;
 const owner=user.id;quoteNoticeLoading=true;
 try{const qs=await result(db.from('rd_quotes').select('id,project_id,amount,created_at').eq('status','pending').order('created_at',{ascending:false}).limit(50));
  if(user?.id!==owner||profile?.role!=='client')return;
  const seen=readQuoteNoticeIds(owner),unread=qs.filter(q=>!seen.has(q.id));
  if(!unread.length){clearQuoteNotice();return;}
  const ps=await result(db.from('rd_projects').select('id,title,client_id').eq('client_id',owner).in('id',[...new Set(unread.map(q=>q.project_id))]));
  if(user?.id!==owner||profile?.role!=='client')return;
  const rows=unread.filter(q=>ps.some(p=>p.id===q.project_id)).map(q=>({...q,project_title:ps.find(p=>p.id===q.project_id).title}));
  const changed=quoteNoticeOwner!==owner||rows.map(q=>q.id).join()!==quoteNoticeRows.map(q=>q.id).join();quoteNoticeOwner=owner;quoteNoticeRows=rows;if(changed)paintQuoteNotice();
 }catch(e){/* A background notification must not interrupt the current form. */}finally{quoteNoticeLoading=false;}
}
function installQuoteNotifications(){
 const css=document.createElement('style');css.id='rd-quote-notice-style';css.textContent=`
 #rd-quote-notice{position:fixed;z-index:350;top:calc(12px + env(safe-area-inset-top));left:50%;transform:translateX(-50%);width:min(410px,calc(100% - 24px));box-sizing:border-box;display:flex;align-items:flex-start;gap:11px;padding:16px 8px 16px 16px;border-radius:20px;background:#fffef4;border:1px solid #d8e2d3;box-shadow:0 12px 36px #173d292b;color:#234731}
 #rd-quote-notice a{flex:1;min-width:0;color:inherit;text-decoration:none}#rd-quote-notice strong,#rd-quote-notice span,#rd-quote-notice b{display:block}#rd-quote-notice strong{font-size:14px;line-height:1.4}#rd-quote-notice a span{font-size:12px;line-height:1.5;margin-top:4px;overflow-wrap:anywhere;color:#64705e}#rd-quote-notice b{font-size:12px;margin-top:8px}#rd-quote-notice .rd-quote-notice-icon{font-size:23px;color:#b99560}#rd-quote-notice button{width:44px;height:44px;flex:0 0 44px;border:0;background:transparent;color:#64705e;font-size:25px;border-radius:12px}#rd-quote-notice a:focus-visible,#rd-quote-notice button:focus-visible{outline:2px solid #315d40;outline-offset:3px}
 `;document.head.append(css);
 document.addEventListener('click',e=>{const dismiss=e.target.closest('[data-dismiss-quotes]'),link=e.target.closest('[data-quote]');if(dismiss){e.preventDefault();e.stopImmediatePropagation();markQuoteNoticeRead(quoteNoticeRows.map(q=>q.id));}else if(link&&profile?.role==='client'){markQuoteNoticeRead([link.dataset.quote]);}},true);
 window.addEventListener('focus',()=>void checkQuoteNotifications());document.addEventListener('visibilitychange',()=>void checkQuoteNotifications());
 setInterval(()=>void checkQuoteNotifications(),10000);
}

function err(e){const text=e?.message||'Connexion impossible. Réessayez.';if(/invalid login/i.test(text))return 'Courriel ou mot de passe incorrect.';if(/email not confirmed/i.test(text))return 'Confirmez votre courriel avant de vous connecter.';if(/rate limit|too many/i.test(text))return 'Trop de tentatives. Patientez un moment puis réessayez.';if(/already registered/i.test(text))return 'Ce courriel a déjà un compte. Connectez-vous.';if(/duplicate key/i.test(text))return 'Vous avez déjà envoyé une soumission pour ce projet.';if(/fetch|network/i.test(text))return 'Vérifiez votre connexion Internet et réessayez.';return text;}
function pageError(message,retry=false){let page=byId(route());if(!page)return;let e=page.querySelector('.rd-live-error');if(!e){e=document.createElement('div');e.className='rd-live-error';e.setAttribute('role','alert');(page.querySelector('.rd-signup-card,.login-card,.rd52,.rd-live-detail,.rd58-shell')||page).append(e);}e.textContent=message;if(retry){const button=document.createElement('button');button.type='button';button.className='rd-live-refresh';button.dataset.refresh='';button.textContent='Réessayer';e.append(document.createElement('br'),button);}e.scrollIntoView({block:'nearest'});}
async function result(request){const {data,error}=await request;if(error)throw error;return data;}
async function action(button,fn){if(busy)return;busy=true;const old=button?.textContent;const disabled=button?.disabled;if(button){if('disabled' in button)button.disabled=true;button.setAttribute('aria-disabled','true');button.textContent='Un instant…';}document.querySelectorAll('.rd-live-error').forEach(e=>e.remove());try{await fn();}catch(e){pageError(err(e));}finally{busy=false;if(button){if('disabled' in button)button.disabled=disabled;button.removeAttribute('aria-disabled');button.textContent=old;}}}
const value=id=>byId(id)?.value.trim()||'';
function required(ok,message){if(!ok)throw Error(message);}
function city(v){const found=cities.find(c=>normalize(c[0])===normalize(v));required(found,'Choisissez votre ville dans les suggestions.');return {city:found[0],latitude:found[1],longitude:found[2]};}
function selectedServices(){return Object.entries(inputServices).filter(([id])=>byId(id).checked).map(([,key])=>key);}
function radius(){return Number(value('rd-territory-field-2')||$('#territory input[name="radius"]:checked')?.id.slice(1)||50);}
function readClient(){required(value('rd-signup-given-name')&&value('rd-signup-family-name'),'Indiquez votre prénom et votre nom.');city(value('rd-signup-address-level2'));return {role:'client',display_name:[value('rd-signup-given-name'),value('rd-signup-family-name')].join(' '),company_name:'',...city(value('rd-signup-address-level2')),services:[],radius_km:50,rbq:'',account_details:{phone:value('rd-signup-tel'),postal:value('rd-signup-postal-code')}};}
function readContractor(){required(value('rd-pro2-field-1'),'Indiquez le nom de votre entreprise.');required(selectedServices().length,'Choisissez au moins un service.');required(Number.isInteger(radius())&&radius()>=1&&radius()<=300,'Le rayon doit être un nombre entier entre 1 et 300 km.');return {role:'contractor',display_name:[value('rd-pro1-field-1'),value('rd-pro1-field-2')].filter(Boolean).join(' ')||profile?.display_name||value('rd-pro2-field-2')||value('rd-pro2-field-1'),company_name:value('rd-pro2-field-2')||value('rd-pro2-field-1'),...city(value('rd-territory-field-1')),services:selectedServices(),radius_km:radius(),rbq:value('rd-pro2-field-7'),account_details:{phone:value('rd-pro2-field-3')||value('rd-pro1-field-4'),legal_company_name:value('rd-pro2-field-1'),address:value('rd-pro2-field-4'),postal:value('rd-pro2-field-6'),website:value('rd-pro2-field-8')}};}
function credentials(kind){const pro=kind==='contractor',email=value(pro?'rd-pro1-field-3':'rd-signup-email'),password=value(pro?'rd-pro1-field-5':'rd-signup-new-password'),confirm=value(pro?'rd-pro1-field-6':'rd-signup-confirm-password');required(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Indiquez un courriel valide.');required(password.length>=8,'Le mot de passe doit contenir au moins 8 caractères.');required(password===confirm,'Les deux mots de passe doivent être identiques.');return {email,password};}
async function signup(kind){const initial=kind==='client'?readClient():readContractor();if(kind==='client')required($('#client .terms input').checked,'Acceptez les conditions avant de créer votre compte.');const c=credentials(kind);signupProfile=initial;
 const {data,error}=await db.auth.signUp({...c,options:{emailRedirectTo:location.origin+'/',data:{initial_profile:initial}}});if(error)throw error;
 if(data.session){user=data.user;await loadProfile();go(kind==='client'?'clientDashboard':'building');}else{go(kind==='client'?'loginClient':'loginPro');notify('Compte créé. Confirmez votre courriel avec le lien reçu, puis connectez-vous.');}
 ['rd-signup-new-password','rd-signup-confirm-password','rd-pro1-field-5','rd-pro1-field-6'].forEach(id=>{if(byId(id))byId(id).value='';});
}
async function loadProfile(){const owner=user?.id;if(profileLoading?.owner===owner)return profileLoading.promise;const promise=loadProfileOnce();profileLoading={owner,promise};try{return await promise;}finally{if(profileLoading?.promise===promise)profileLoading=null;}}
async function loadProfileOnce(){const owner=user?.id,metadata=user?.user_metadata;if(!owner){profile=null;accountDetails=null;return;}
 let loaded=await result(db.from('rd_profiles').select('*').eq('id',owner).maybeSingle());if(user?.id!==owner)return;
 if(!loaded){const pending=signupProfile||metadata?.initial_profile;if(pending){const allowed=['role','display_name','company_name','city','latitude','longitude','services','radius_km','rbq'];const row=Object.fromEntries(allowed.map(k=>[k,pending[k]]));loaded=await result(db.from('rd_profiles').insert({id:owner,...row}).select().single());if(user?.id!==owner)return;signupProfile=null;}}
 let details=null;if(loaded){details=await result(db.from('rd_account_details').select('*').eq('id',owner).maybeSingle());if(user?.id!==owner)return;const initial=metadata?.initial_profile?.account_details;if(!details&&initial)details=await result(db.from('rd_account_details').insert({id:owner,...initial}).select().single());}if(user?.id===owner){profile=loaded;accountDetails=details;}
}
async function login(kind){const screen=byId(kind==='client'?'loginClient':'loginPro'),email=screen.querySelector('input[type="email"]').value.trim(),password=screen.querySelector('input[type="password"]').value;required(email&&password,'Indiquez votre courriel et votre mot de passe.');const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;user=data.user;await loadProfile();required(profile,'Votre profil est incomplet. Complétez votre inscription.');if(profile.role!==kind){await db.auth.signOut();user=null;profile=null;throw Error('Ce compte est un compte '+(kind==='client'?'entrepreneur. Utilisez la connexion entrepreneur.':'client. Utilisez la connexion client.'));}screen.querySelector('input[type="password"]').value='';go(kind==='client'?'clientDashboard':'contractorFeed');}
function remember(key,id){try{if(user)localStorage.setItem('rd-live-'+user.id+'-'+key,id);}catch(e){}}
function recall(key){try{return user?localStorage.getItem('rd-live-'+user.id+'-'+key):null;}catch(e){return null;}}
async function project(id){if(!id)return null;return await result(db.from('rd_projects').select('*').eq('id',id).maybeSingle());}
async function quote(id){if(!id)return null;return await result(db.from('rd_quotes').select('*').eq('id',id).maybeSingle());}
function empty(text){return '<div class="rd-live-empty">'+esc(text)+'</div>';}
function card(p,link,extra=''){return '<a class="rd-live-card" href="#'+link+'" data-project="'+p.id+'"><div class="rd-live-meta"><span class="rd-live-status">'+esc(labels[p.status])+'</span><span>'+esc(p.city)+'</span></div><h3>'+esc(p.title)+'</h3><p>'+esc(p.description.slice(0,180))+'</p><div class="rd-live-meta"><span>'+esc(services[p.service])+'</span><span>'+esc(p.budget)+'</span></div>'+extra+'</a>';}
function back(id,text='Retour'){return '<a class="rd-live-back" aria-label="Retour" href="#'+id+'">← '+esc(text)+'</a>';}
function paint(host,content){if(host.dataset.content===content)return;host.innerHTML=content;host.dataset.content=content;}
function shell(id,content){paint(byId(id),'<div class="rd-live-detail">'+content+'</div>');}
function nav(pro){return '<nav class="rd-live-nav"><a href="#'+(pro?'contractorFeed':'clientDashboard')+'">Accueil</a><a href="#'+(pro?'contractorQuotes':'clientProjects')+'">'+(pro?'Soumissions':'Projets')+'</a><a href="#clientMessages">Messages</a><a href="#'+(pro?'profilePreview':'clientDashboard')+'" '+(pro?'':'data-account="1"')+'>Profil</a></nav>';}
function person(p){return p?.company_name||p?.display_name||'Entrepreneur';}
async function profiles(ids){if(!ids.length)return {};const rows=await result(db.from('rd_profiles').select('*').in('id',[...new Set(ids)]));return Object.fromEntries(rows.map(p=>[p.id,p]));}
async function ownProjects(){return result(db.from('rd_projects').select('*').eq('client_id',user.id).order('created_at',{ascending:false}));}
async function ownQuotes(){return result(db.from('rd_quotes').select('*').eq('contractor_id',user.id).order('created_at',{ascending:false}));}
async function renderDashboard(version){const ps=await ownProjects();if(version!==routeVersion)return;const active=ps.filter(p=>!['archived','completed'].includes(p.status));$('#clientDashboard .rd51-head h1').textContent='Bonjour, '+profile.display_name.split(' ')[0]+'.';$('#clientDashboard .rd51-avatar').textContent=profile.display_name.split(' ').map(n=>n[0]).join('').slice(0,2);
 const section=$('#clientDashboard .rd51-section');section.querySelector('.rd51-section-title>span').textContent=active.length+' actif'+(active.length>1?'s':'');const cards=active.length?active.slice(0,3).map(p=>card(p,'clientProjectDetail')).join(''):empty('Aucun projet publié. Décrivez vos travaux pour recevoir des soumissions.');if(section.dataset.cards!==cards){section.querySelectorAll('.rd51-project,.rd-live-card,.rd-live-empty').forEach(e=>e.remove());section.insertAdjacentHTML('beforeend',cards);section.dataset.cards=cards;}
 const activity=$('#clientDashboard .rd79-activity');if(activity)paint(activity,'<div class="rd51-section-title"><h2>Activité récente</h2><button class="rd-live-refresh" data-refresh>Actualiser</button></div>'+ (ps.length?ps.slice(0,2).map(p=>'<a class="rd-live-card" href="#clientProjectDetail" data-project="'+p.id+'"><strong>'+esc(p.title)+'</strong><p>'+esc(labels[p.status])+'</p></a>').join(''):empty('Vos projets et leurs mises à jour apparaîtront ici.')));
 const link=$('#clientDashboard .rd51-quick a[href="#clientProjectDetail"]')||[...byId('clientDashboard').querySelectorAll('a')].find(a=>a.textContent.includes('Soumissions')&&a.closest('nav')===null);if(link)link.setAttribute('href','#clientProjects');byId('rd79PublishedActivity')?.remove();
}
async function renderClientProjects(version){const ps=await ownProjects();if(version!==routeVersion)return;const shown=ps.filter(p=>projectTab==='active'?!['completed','archived'].includes(p.status):p.status===projectTab);shell('clientProjects',back('clientDashboard')+'<h1 class="rd-live-heading">Mes projets</h1><div class="rd-live-tabs"><button data-project-tab="active" class="'+(projectTab==='active'?'active':'')+'">En cours</button><button data-project-tab="completed" class="'+(projectTab==='completed'?'active':'')+'">Terminés</button><button data-project-tab="archived" class="'+(projectTab==='archived'?'active':'')+'">Archivés</button></div>'+(shown.length?shown.map(p=>card(p,'clientProjectDetail')).join(''):empty('Aucun projet dans cette catégorie.'))+'<a class="rd-live-button" href="#newProject">Créer un projet →</a>'+nav(false));}
async function renderFeed(version){const ps=await result(db.from('rd_projects').select('*').eq('status','open').order('created_at',{ascending:false}));if(version!==routeVersion)return;byId('rd87MatchCount').textContent=ps.length;paint(byId('rd62LiveProjects'),ps.length?ps.map(p=>card(p,'contractorProject')).join(''):empty('Aucun projet correspondant à vos services et à votre territoire pour le moment.'));$('#contractorFeed .rd58-prohead h1').textContent='Bonjour, '+profile.display_name.split(' ')[0]+'.';$('#contractorFeed .rd58-why p').textContent='Services : '+profile.services.map(s=>services[s]).join(', ')+'. Territoire : '+profile.city+' + '+profile.radius_km+' km. Distances estimées entre centres des villes.';}
async function loadSelectedProject(){const id=selectedProject?.id||recall('project'),owner=user?.id,p=await project(id);required(p,'Projet introuvable ou inaccessible.');if(user?.id===owner&&(selectedProject?.id||recall('project'))===id)selectedProject=p;return p;}
async function loadSelectedQuote(){const id=selectedQuote?.id||recall('quote'),owner=user?.id,q=await quote(id);required(q,'Soumission introuvable ou inaccessible.');if(user?.id===owner&&(selectedQuote?.id||recall('quote'))===id)selectedQuote=q;return q;}
async function photoHTML(p){const photos=await result(db.from('rd_project_photos').select('path').eq('project_id',p.id));if(!photos.length)return '';const signed=await result(db.storage.from('rd-project-photos').createSignedUrls(photos.map(x=>x.path),3600));return '<div class="rd-live-photo-grid">'+signed.filter(x=>x.signedUrl).map(x=>'<a href="'+esc(x.signedUrl)+'" target="_blank" rel="noopener"><img src="'+esc(x.signedUrl)+'" alt="Photo du projet"></a>').join('')+'</div>';}
async function renderProject(pro,version){const p=await loadSelectedProject(),qs=pro?[]:await result(db.from('rd_quotes').select('*').eq('project_id',p.id).order('created_at',{ascending:false}));const names=await profiles(qs.map(q=>q.contractor_id)),photos=await photoHTML(p);if(version!==routeVersion)return;let content=back(pro?'contractorFeed':'clientProjects')+'<h1 class="rd-live-heading">'+esc(p.title)+'</h1><div class="rd-live-meta"><span class="rd-live-status">'+esc(labels[p.status])+'</span><span>'+esc(p.city)+'</span></div><div class="rd-live-card"><strong>'+esc(services[p.service])+'</strong><p>'+esc(p.description)+'</p><div class="rd-live-meta"><span>'+esc(p.budget)+'</span><span>'+esc(p.timing)+'</span></div></div>'+photos;
 if(pro){const sent=await result(db.from('rd_quotes').select('id').eq('project_id',p.id).eq('contractor_id',user.id).maybeSingle());content+=p.status==='open'&&!sent?'<a class="rd-live-button" href="#contractorBid">Préparer une soumission →</a>':sent?'<a class="rd-live-button" href="#quoteDetail" data-quote="'+sent.id+'">Consulter ma soumission →</a>':empty('Ce projet n’accepte plus de soumissions.');}
 else {content+='<h2>Soumissions reçues ('+qs.length+')</h2>'+(qs.length?qs.map(q=>quoteCard(q,names[q.contractor_id])).join(''):empty('Aucune soumission pour le moment. Les entrepreneurs correspondant à votre projet peuvent maintenant le consulter.'));if(['accepted','in_progress'].includes(p.status))content+='<button class="rd-live-button" data-progress="'+(p.status==='accepted'?'in_progress':'completed')+'">'+(p.status==='accepted'?'Indiquer le début des travaux':'Confirmer que les travaux sont terminés')+'</button>';if(p.status==='open')content+='<button class="rd-live-button secondary" data-progress="archived">Archiver le projet</button>';}
 if(version!==routeVersion)return;shell(pro?'contractorProject':'clientProjectDetail',content);
}
function quoteCard(q,who,p){return '<a class="rd-live-card" href="#quoteDetail" data-quote="'+q.id+'"><div class="rd-live-meta"><strong>'+esc(who?person(who):p?.title||'Soumission')+'</strong><span class="rd-live-status">'+esc(labels[p?.status==='completed'&&q.status==='accepted'?'completed':q.status])+'</span></div><h3>'+money(q.amount)+'</h3><p>'+esc(q.duration)+' · Début : '+esc(q.start_date)+'</p></a>';}
async function renderQuote(version){const q=await loadSelectedQuote(),p=await project(q.project_id);required(p,'Ce projet n’est plus accessible.');const names=await profiles([q.contractor_id,p.client_id]);if(version!==routeVersion)return;selectedProject=p;remember('project',p.id);
 let content=back(profile.role==='client'?'clientProjectDetail':'contractorQuotes')+'<span class="rd-live-status">'+esc(labels[p.status==='completed'&&q.status==='accepted'?'completed':q.status])+'</span><h1 class="rd-live-heading">'+esc(person(names[q.contractor_id]))+'</h1><p class="rd-live-copy">'+esc(p.title)+'</p><div class="rd-live-card"><h2>'+money(q.amount)+'</h2><p>Durée : '+esc(q.duration)+'<br>Début proposé : '+esc(q.start_date)+'</p><p>'+esc(q.message)+'</p></div><a class="rd-live-button secondary" href="#clientChat" data-quote="'+q.id+'">Discuter →</a>';
 if(profile.role==='client')content+='<a class="rd-live-button secondary" href="#businessProfile" data-business="'+q.contractor_id+'">Voir le profil de l’entreprise →</a>';
 if(profile.role==='client'&&q.status==='pending'&&p.status==='open')content+='<button class="rd-live-button" data-accept="'+q.id+'">Choisir cet entrepreneur →</button><p class="rd-live-copy">Les autres soumissions seront indiquées comme non retenues. Confirmez les modalités avec l’entrepreneur avant le début des travaux.</p>';
 if(q.status==='accepted'&&p.status==='accepted')content+='<button class="rd-live-button" data-progress="in_progress">Indiquer le début des travaux</button>';
 if(profile.role==='client'&&q.status==='accepted'&&p.status==='in_progress')content+='<button class="rd-live-button" data-progress="completed">Confirmer que les travaux sont terminés</button>';
 const contractor=names[q.contractor_id];if(contractor)content+='<div class="rd-live-card"><h2>Entreprise</h2><p>'+esc(contractor.city)+' · '+contractor.services.map(s=>esc(services[s])).join(', ')+'</p><p>Licence RBQ déclarée : '+esc(contractor.rbq||'Non renseignée')+'</p></div>';
 shell('quoteDetail',content);
}
async function renderBid(version){const p=await loadSelectedProject();required(p.status==='open','Ce projet n’accepte plus de soumissions.');if(version!==routeVersion)return;shell('contractorBid',back('contractorProject')+'<p class="rd-live-copy">'+esc(p.title)+'</p><h1 class="rd-live-heading">Votre soumission</h1><form id="rd-live-bid"><label for="rd-bid-amount">Prix total proposé ($)</label><input id="rd-bid-amount" type="number" min="0.01" step="0.01" max="9999999999" required inputmode="decimal"><label for="rd-bid-duration">Durée estimée des travaux</label><input id="rd-bid-duration" placeholder="Ex. 2 jours ou 3 semaines" maxlength="120" required><label for="rd-bid-date">Date de début possible</label><input id="rd-bid-date" type="date" required><label for="rd-bid-message">Détail de l’offre et message au client</label><textarea id="rd-bid-message" minlength="10" maxlength="10000" placeholder="Expliquez les travaux inclus, les exclusions et vos disponibilités." required></textarea><p class="rd-live-copy">Précisez dans votre offre si les taxes sont incluses.</p><button class="rd-live-button" type="submit">Envoyer la soumission →</button></form>');restoreForm('rd-live-bid');}
async function renderQuotes(version){const qs=await ownQuotes(),ps=qs.length?await result(db.from('rd_projects').select('*').in('id',qs.map(q=>q.project_id))):[];if(version!==routeVersion)return;const pm=Object.fromEntries(ps.map(p=>[p.id,p]));const shown=qs.filter(q=>quoteTab==='completed'?q.status==='accepted'&&pm[q.project_id]?.status==='completed':q.status===quoteTab&&!(q.status==='accepted'&&pm[q.project_id]?.status==='completed'));shell('contractorQuotes',back('contractorFeed')+'<h1 class="rd-live-heading">Mes soumissions</h1><div class="rd-live-tabs">'+[['pending','En attente'],['accepted','Acceptées'],['completed','Terminées'],['declined','Non retenues']].map(([k,t])=>'<button data-quote-tab="'+k+'" class="'+(quoteTab===k?'active':'')+'">'+t+'</button>').join('')+'</div>'+(shown.length?shown.map(q=>quoteCard(q,null,pm[q.project_id])).join(''):empty('Aucune soumission dans cette catégorie.'))+nav(true));}
async function renderAccepted(version){const q=await loadSelectedQuote(),p=await project(q.project_id);if(version!==routeVersion)return;required(p,'Ce projet n’est plus accessible.');shell('quoteAccepted',back(profile.role==='contractor'?'contractorQuotes':'clientProjectDetail')+'<h1 class="rd-live-heading">Entrepreneur choisi.</h1><p class="rd-live-copy">Le projet « '+esc(p.title)+' » est maintenant attribué. Retrouvez votre soumission et la conversation pour organiser les travaux.</p><a href="#quoteDetail" class="rd-live-button">Voir la soumission →</a><a href="#clientChat" class="rd-live-button secondary">Discuter →</a>');}
async function renderMessages(version){const qs=await result(db.from('rd_quotes').select('*').order('created_at',{ascending:false})),ps=qs.length?await result(db.from('rd_projects').select('*').in('id',qs.map(q=>q.project_id))):[],names=await profiles(qs.map(q=>profile.role==='client'?q.contractor_id:ps.find(p=>p.id===q.project_id)?.client_id).filter(Boolean));if(version!==routeVersion)return;
 shell('clientMessages',back(profile.role==='client'?'clientDashboard':'contractorFeed')+'<h1 class="rd-live-heading">Messages</h1>'+(qs.length?qs.map(q=>{const p=ps.find(x=>x.id===q.project_id),other=names[profile.role==='client'?q.contractor_id:p?.client_id];return '<a class="rd-live-card" href="#clientChat" data-quote="'+q.id+'"><strong>'+esc(person(other))+'</strong><p>'+esc(p?.title||'Projet')+'</p><span class="rd-live-status">'+esc(labels[q.status])+'</span></a>';}).join(''):empty('Vos conversations apparaîtront après l’envoi d’une soumission.'))+nav(profile.role==='contractor'));}
async function chatMessages(){const id=selectedQuote?.id||recall('quote'),owner=user?.id,version=routeVersion;if(!id||!byId('rd-live-chat-messages'))return;const rows=await result(db.from('rd_messages').select('*').eq('quote_id',id).order('created_at'));if(route()!=='clientChat'||owner!==user?.id||version!==routeVersion||id!==(selectedQuote?.id||recall('quote')))return;const host=byId('rd-live-chat-messages'),current=byId('clientChat'),bottom=current.scrollHeight-current.scrollTop-current.clientHeight<100;paint(host,rows.length?rows.map(m=>'<div class="rd-live-bubble '+(m.sender_id===user.id?'mine':'')+'">'+esc(m.body)+'<small>'+new Date(m.created_at).toLocaleString('fr-CA')+'</small></div>').join(''):empty('Commencez la conversation pour préciser les travaux et vos disponibilités.'));if(bottom)current.scrollTop=current.scrollHeight;}
const formDrafts=new Map();
function formKey(id){return user?.id+':'+id+':'+(id==='rd-live-chat-form'?selectedQuote?.id:selectedProject?.id);}
function saveForm(form){if(!user)return;formDrafts.set(formKey(form.id),Object.fromEntries([...form.querySelectorAll('input,textarea')].map(e=>[e.id,e.value])));}
function restoreForm(id){const saved=formDrafts.get(formKey(id));if(saved)Object.entries(saved).forEach(([key,v])=>{if(byId(key))byId(key).value=v;});}
async function renderChat(version){const q=await loadSelectedQuote(),p=await project(q.project_id);if(version!==routeVersion)return;shell('clientChat',back('clientMessages')+'<h1 class="rd-live-heading">'+esc(p?.title||'Conversation')+'</h1><a href="#quoteDetail">Voir la soumission →</a><div id="rd-live-chat-messages"></div><form id="rd-live-chat-form"><label for="rd-live-message">Votre message</label><textarea id="rd-live-message" maxlength="4000" required placeholder="Écrivez votre message…"></textarea><button class="rd-live-button" type="submit">Envoyer →</button></form>');restoreForm('rd-live-chat-form');await chatMessages();}
function fillProfile(){if(profile?.role!=='contractor')return;const p=profile;const back=$('#pro2 a.back');if(back)back.href='#contractorFeed';byId('rd-pro2-field-1').value=accountDetails?.legal_company_name||p.company_name;byId('rd-pro2-field-2').value=p.company_name;Object.entries({'rd-pro2-field-3':'phone','rd-pro2-field-4':'address','rd-pro2-field-6':'postal','rd-pro2-field-8':'website'}).forEach(([id,k])=>byId(id).value=accountDetails?.[k]||'');byId('rd-pro2-field-5').value=p.city;byId('rd-pro2-field-7').value=p.rbq;byId('rd-territory-field-1').value=p.city;byId('rd-territory-field-2').value=p.radius_km;Object.entries(inputServices).forEach(([id,k])=>byId(id).checked=p.services.includes(k));}
let selectedBusiness=null,businessEditing=false,portfolioEditing=null,businessPortfolio=[],coverPreviewURL=null,coverCrop=null,coverDrag=null;
function clearCoverPreview(){coverCrop=null;coverDrag=null;if(coverPreviewURL){URL.revokeObjectURL(coverPreviewURL);coverPreviewURL=null;}}
function coverGeometry(crop,cover){const width=cover.clientWidth||360,height=cover.clientHeight||215,scale=Math.max(width/crop.width,height/crop.height)*crop.zoom;return {width,height,scale,overflowX:Math.max(0,crop.width*scale-width),overflowY:Math.max(0,crop.height*scale-height)};}
function positionCover(){if(!coverCrop)return;const cover=$('#profilePreview .rd-business-cover'),image=cover?.querySelector(':scope > img');if(!image)return;const g=coverGeometry(coverCrop,cover);Object.assign(image.style,{position:'absolute',width:coverCrop.width*g.scale+'px',height:coverCrop.height*g.scale+'px',maxWidth:'none',left:-g.overflowX*coverCrop.x+'px',top:-g.overflowY*coverCrop.y+'px'});}
async function previewCover(input){const file=input.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10485760){input.value='';notify('Choisissez une image JPG, PNG ou WebP de moins de 10 Mo.');return;}clearCoverPreview();const url=URL.createObjectURL(file);coverPreviewURL=url;const source=new Image();source.src=url;try{await source.decode();}catch(e){if(coverPreviewURL===url){clearCoverPreview();input.value='';notify('Impossible de lire cette photo. Choisissez une autre image.');}return;}if(coverPreviewURL!==url||!input.isConnected||input.files?.[0]!==file)return;coverCrop={file,source,width:source.naturalWidth||source.width,height:source.naturalHeight||source.height,zoom:1,x:.5,y:.5};const cover=input.closest('.rd-business-cover');cover.querySelector(':scope > img')?.remove();cover.querySelector(':scope > span:not(.rd-business-cover-label)')?.remove();cover.classList.remove('is-empty');cover.classList.add('rd-cover-cropping');const image=document.createElement('img');image.src=url;image.alt='Aperçu du cadrage de votre couverture';image.draggable=false;cover.prepend(image);let controls=byId('rd-cover-controls');if(!controls){controls=document.createElement('div');controls.id='rd-cover-controls';controls.className='rd-cover-controls';controls.innerHTML='<p>Glissez la photo pour ajuster son cadrage.</p><div><label for="rd-cover-zoom">Zoom</label><input id="rd-cover-zoom" type="range" min="1" max="3" step="0.01" value="1" aria-label="Zoom de la couverture"><button type="button" data-cover-reset>Recentrer</button></div><small>Le cadrage sera conservé avec « Enregistrer la présentation ».</small>';cover.after(controls);}byId('rd-cover-zoom').value='1';positionCover();}
async function croppedCover(file){if(!coverCrop||coverCrop.file!==file)return compressPhoto(file);const crop={...coverCrop},cover=$('#profilePreview .rd-business-cover'),g=coverGeometry(crop,cover),canvas=document.createElement('canvas');canvas.width=1600;canvas.height=Math.round(1600*g.height/g.width);canvas.getContext('2d').drawImage(crop.source,g.overflowX*crop.x/g.scale,g.overflowY*crop.y/g.scale,g.width/g.scale,g.height/g.scale,0,0,canvas.width,canvas.height);return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));}
const businessUploadFields={cover:'rd-business-cover',logo:'rd-business-logo',before:'rd-portfolio-before',after:'rd-portfolio-after'};
function businessInput(id,label,v='',extra=''){return '<label for="'+id+'">'+label+'</label><input id="'+id+'" value="'+esc(v)+'" '+extra+'>';}
function businessPhotoInput(id,label){return '<label class="rd-business-upload" for="'+id+'">'+label+'<input id="'+id+'" type="file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG ou WebP · 10 Mo maximum</small></label>';}
async function businessPhoto(kind,owner){const file=byId(businessUploadFields[kind])?.files?.[0];if(!file)return null;required(['image/jpeg','image/png','image/webp'].includes(file.type)&&file.size<=10485760,'Choisissez une image JPG, PNG ou WebP de moins de 10 Mo.');const blob=await (kind==='cover'?croppedCover(file):compressPhoto(file));required(blob,'Impossible de préparer cette photo.');required(user?.id===owner,'Reconnectez-vous avant d’enregistrer.');const path=owner+'/'+crypto.randomUUID()+'.jpg';await result(db.storage.from('rd-business-media').upload(path,blob,{contentType:'image/jpeg',upsert:false}));return path;}
async function saveBusinessForm(form,finish=true){required(profile?.role==='contractor'&&route()==='profilePreview','Ce profil appartient à un compte entrepreneur.');const owner=user.id,version=routeVersion;
 if(form.id==='rd-business-form'){const years=value('rd-business-years'),row={id:owner,tagline:value('rd-business-tagline'),bio:value('rd-business-bio'),experience_years:years===''?null:Number(years),insurance_declared:byId('rd-business-insurance').checked};required(row.experience_years===null||Number.isInteger(row.experience_years)&&row.experience_years>=0&&row.experience_years<=100,'Indiquez un nombre d’années valide.');for(const kind of ['cover','logo']){const path=await businessPhoto(kind,owner);if(path)row[kind+'_path']=path;}required(user?.id===owner,'Reconnectez-vous avant d’enregistrer.');await result(db.from('rd_business_pages').upsert(row));}
 else {const editing=portfolioEditing,existing=businessPortfolio.find(x=>x.id===editing),row={title:value('rd-portfolio-title'),city:value('rd-portfolio-city'),description:value('rd-portfolio-description'),before_path:existing?.before_path||null,after_path:existing?.after_path||null};required(row.title,'Donnez un titre à votre réalisation.');for(const kind of ['before','after']){const path=await businessPhoto(kind,owner);if(path)row[kind+'_path']=path;}required(row.before_path||row.after_path,'Ajoutez au moins une photo de cette réalisation.');required(user?.id===owner,'Reconnectez-vous avant d’enregistrer.');await result(editing?db.from('rd_portfolio').update(row).eq('id',editing).eq('contractor_id',owner):db.from('rd_portfolio').insert({...row,contractor_id:owner}));}
 if(finish){if(user?.id===owner&&version===routeVersion&&route()==='profilePreview'){businessEditing=false;portfolioEditing=null;await render();}notify('Profil professionnel enregistré.');}
}
async function saveBusinessChanges(){required(profile?.role==='contractor'&&route()==='profilePreview'&&businessEditing,'Ouvrez la modification de votre profil.');const owner=user.id,version=routeVersion,presentation=byId('rd-business-form'),portfolio=byId('rd-portfolio-form'),existing=businessPortfolio.find(x=>x.id===portfolioEditing),hasPortfolio=Boolean(portfolioEditing||['rd-portfolio-title','rd-portfolio-city','rd-portfolio-description'].some(id=>value(id))||['before','after'].some(kind=>byId(businessUploadFields[kind])?.files?.length));if(!presentation.reportValidity()||(hasPortfolio&&!portfolio.reportValidity()))return;
 for(const id of Object.values(businessUploadFields)){const file=byId(id)?.files?.[0];if(file)required(['image/jpeg','image/png','image/webp'].includes(file.type)&&file.size<=10485760,'Choisissez une image JPG, PNG ou WebP de moins de 10 Mo.');}
 if(hasPortfolio)required(existing?.before_path||existing?.after_path||['before','after'].some(kind=>byId(businessUploadFields[kind])?.files?.length),'Ajoutez au moins une photo de cette réalisation.');
 await saveBusinessForm(presentation,false);required(user?.id===owner&&routeVersion===version&&route()==='profilePreview','La présentation a été enregistrée. Revenez au profil pour terminer les autres changements.');if(hasPortfolio)await saveBusinessForm(portfolio,false);if(user?.id===owner&&version===routeVersion&&route()==='profilePreview'){businessEditing=false;portfolioEditing=null;await render();}notify('Tous les changements du profil ont été sauvegardés.');
}
async function renderBusinessProfile(version){const own=route()==='profilePreview',owner=user.id,target=own?owner:selectedBusiness||recall('business');required(target,'Sélectionnez une entreprise depuis sa soumission.');const p=own?profile:await result(db.from('rd_profiles').select('*').eq('id',target).maybeSingle());required(p?.role==='contractor','Profil introuvable ou inaccessible.');const [page,portfolio]=await Promise.all([result(db.from('rd_business_pages').select('*').eq('id',target).maybeSingle()),result(db.from('rd_portfolio').select('*').eq('contractor_id',target).order('created_at',{ascending:false}))]);const b=page||{},paths=[b.cover_path,b.logo_path,...portfolio.flatMap(x=>[x.before_path,x.after_path])].filter(Boolean),urls={};if(paths.length){const signed=await result(db.storage.from('rd-business-media').createSignedUrls([...new Set(paths)],900));signed.forEach(x=>{if(x.signedUrl)urls[x.path]=x.signedUrl;});}if(version!==routeVersion||user?.id!==owner)return;businessPortfolio=own?portfolio:[];
 const image=(path,alt)=>urls[path]?'<img src="'+esc(urls[path])+'" alt="'+esc(alt)+'" loading="lazy">':'<div class="rd-business-no-photo">Photo indisponible</div>',initials=person(p).split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
 let content='<div class="rd-business"><header class="rd-business-top"><a class="back rd-live-back" href="#'+(own?'contractorFeed':'quoteDetail')+'" aria-label="Retour">‹</a><span>'+(own?'Mon entreprise':'Profil de l’entreprise')+'</span>'+(own?(businessEditing?'<button type="button" data-business-save>Sauvegarder les changements</button>':'<button type="button" data-business-edit="1">Modifier</button>'):'')+'</header><div class="rd-business-cover '+(urls[b.cover_path]?'':'is-empty')+'">'+(urls[b.cover_path]?image(b.cover_path,'Photo de couverture de '+person(p)):'<span>Votre savoir-faire.<br>Votre signature.</span>')+'<span class="rd-business-cover-label">RÉNODIRECT · PROFESSIONNEL</span>'+(own&&businessEditing?'<label class="rd-business-cover-edit" for="rd-business-cover"><span>Modifier la couverture</span><input id="rd-business-cover" type="file" accept="image/jpeg,image/png,image/webp" form="rd-business-form"></label>':'')+'</div><div class="rd-business-identity"><div class="rd-business-logo">'+(urls[b.logo_path]?image(b.logo_path,'Logo de '+person(p)):esc(initials))+'</div><p class="rd-business-eyebrow">'+esc(p.city)+'</p><h1>'+esc(person(p))+'</h1><p class="rd-business-tagline">'+esc(b.tagline||'Un savoir-faire au service de vos projets.')+'</p></div>';
 if(own&&businessEditing){const item=portfolio.find(x=>x.id===portfolioEditing)||{};content+='<section class="rd-business-section"><h2>Votre présentation</h2><p>Ajoutez vos propres photos et présentez ce qui distingue votre entreprise.</p><form id="rd-business-form">'+businessInput('rd-business-tagline','Votre signature',b.tagline,'maxlength="120" placeholder="Des espaces soignés, jusque dans les détails."')+'<label for="rd-business-bio">À propos de l’entreprise</label><textarea id="rd-business-bio" maxlength="3000" rows="5">'+esc(b.bio)+'</textarea>'+businessInput('rd-business-years','Années d’expérience (facultatif)',b.experience_years??'','type="number" min="0" max="100" step="1"')+'<label class="rd-business-check"><input type="checkbox" id="rd-business-insurance" '+(b.insurance_declared?'checked':'')+'> Assurance responsabilité déclarée</label>'+'<p>Pour changer la photo de couverture, touchez le grand visuel en haut. La photo sera enregistrée avec votre présentation.</p>'+businessPhotoInput('rd-business-logo','Logo de l’entreprise')+'<button type="submit" class="rd-live-button">Enregistrer la présentation →</button></form><a class="mp-edit rd-live-button secondary" href="#pro2">Modifier les informations, services et territoire</a></section><section class="rd-business-section"><h2>'+(portfolioEditing?'Modifier la réalisation':'Ajouter une réalisation')+'</h2><form id="rd-portfolio-form">'+businessInput('rd-portfolio-title','Titre',item.title,'maxlength="120" required')+businessInput('rd-portfolio-city','Ville (facultatif)',item.city,'maxlength="120"')+'<label for="rd-portfolio-description">Description</label><textarea id="rd-portfolio-description" maxlength="1500" rows="3">'+esc(item.description)+'</textarea>'+businessPhotoInput('rd-portfolio-before','Photo avant (facultatif)')+businessPhotoInput('rd-portfolio-after','Photo après')+'<p>Une photo minimum. Pour une réalisation existante, les photos sont conservées si vous n’en choisissez pas de nouvelles. Publiez uniquement des images que vous avez le droit d’utiliser, sans renseignements privés de clients.</p><button type="submit" class="rd-live-button">'+(portfolioEditing?'Enregistrer les modifications':'Ajouter au portfolio')+' →</button></form></section>';}
 else {content+='<div class="rd-business-facts"><div><strong>'+p.services.length+'</strong><span>spécialité'+(p.services.length>1?'s':'')+'</span></div><div><strong>'+p.radius_km+'<small> km</small></strong><span>rayon de service</span></div>'+(b.experience_years!==null&&b.experience_years!==undefined?'<div><strong>'+b.experience_years+'<small> ans</small></strong><span>d’expérience déclarée</span></div>':'')+'</div><section class="rd-business-section"><h2>Le savoir-faire, en quelques mots.</h2><p class="rd-business-bio">'+esc(b.bio||(own?'Présentez votre équipe, votre approche et ce qui fait la différence. Touchez « Modifier » pour personnaliser votre vitrine.':'Cette entreprise n’a pas encore ajouté de présentation.'))+'</p><div class="rd-business-chips">'+p.services.map(k=>'<span>'+esc(services[k]||k)+'</span>').join('')+'</div></section>';}
 content+='<section class="rd-business-section"><div class="rd-business-section-head"><h2>Nos réalisations</h2><span>'+portfolio.length+'</span></div>'+(portfolio.length?portfolio.map(x=>'<article class="rd-business-project"><div class="rd-business-pair">'+[['before_path','Avant'],['after_path','Après']].filter(([k])=>x[k]).map(([k,label])=>'<figure>'+image(x[k],label+' · '+x.title)+'<figcaption>'+label+'</figcaption></figure>').join('')+'</div><div class="rd-business-project-copy"><h3>'+esc(x.title)+'</h3>'+(x.city?'<small>'+esc(x.city)+'</small>':'')+(x.description?'<p>'+esc(x.description)+'</p>':'')+(own?'<button data-portfolio-edit="'+x.id+'">Modifier cette réalisation →</button>':'')+'</div></article>').join(''):'<div class="rd-business-empty">'+(own?'Vos réalisations méritent leur place ici. Ajoutez vos premiers projets dans « Modifier ».':'Les réalisations de cette entreprise seront présentées ici.')+'</div>')+'</section><section class="rd-business-section rd-business-territory"><p class="rd-business-eyebrow">ZONE DE SERVICE</p><h2>'+esc(p.city)+' et les environs</h2><p>Rayon estimé de '+p.radius_km+' km entre centres des villes.</p></section><section class="rd-business-section"><h2>Informations professionnelles</h2><div class="rd-business-declaration"><strong>Licence RBQ déclarée</strong><span>'+esc(p.rbq||'Non renseignée')+'</span></div>'+(b.insurance_declared?'<div class="rd-business-declaration"><strong>Assurance responsabilité</strong><span>Déclarée par l’entreprise</span></div>':'')+'<p class="rd-business-disclaimer">Informations déclarées par l’entrepreneur, non vérifiées par RénoDirect. Confirmez les licences et assurances avant de conclure une entente.</p></section>'+(own?'<p class="rd-business-private">Votre vitrine est visible pour vous et les clients auxquels vous avez envoyé une soumission. Vos coordonnées de compte restent privées.</p>':'<a class="rd-live-button" href="#clientChat">Discuter de mon projet →</a>')+'</div>';
 clearCoverPreview();paint(byId(own?'profilePreview':'businessProfile'),content);
}
let renderedRoute='';
async function render(){guardSessionRoute();const r=route(),version=++routeVersion;byId(r)?.querySelectorAll('.rd-live-error').forEach(e=>e.remove());if(!r||r==='intro'||r==='accueil'||r.startsWith('access_token'))return;
 const requiredRole=(contractorRoutes.has(r)||r==='profilePreview'||r==='building')?'contractor':clientRoutes.has(r)?'client':null;
 if(requiredRole||sharedRoutes.has(r)||r==='profilePreview'||r==='building'){
  if(!user||!profile){go(requiredRole==='contractor'||['profilePreview','building'].includes(r)?'loginPro':'loginClient');return;}
  if(requiredRole&&profile.role!==requiredRole){notify('Ce menu appartient à un compte '+(requiredRole==='client'?'client':'entrepreneur')+'.');go(profile.role==='client'?'clientDashboard':'contractorFeed');return;}
 }
 if(renderedRoute!==r){renderedRoute=r;if(r==='contractorFeed'){paint(byId('rd62LiveProjects'),empty('Chargement des projets…'));byId('rd87MatchCount').textContent='…';}if(r==='clientDashboard'){const section=$('#clientDashboard .rd51-section');section.querySelectorAll('.rd51-project,.rd-live-card,.rd-live-empty').forEach(e=>e.remove());section.dataset.cards='';section.insertAdjacentHTML('beforeend',empty('Chargement de vos projets…'));const activity=$('#clientDashboard .rd79-activity');if(activity)paint(activity,empty('Chargement…'));}if(['profilePreview','businessProfile'].includes(r))paint(byId(r),'<div class="rd-business"><p role="status">Chargement du profil…</p></div>');if(['clientProjects','clientProjectDetail','contractorProject','contractorBid','quoteDetail','contractorQuotes','quoteAccepted','clientMessages','clientChat'].includes(r))shell(r,'<p class="rd-live-copy" role="status">Chargement…</p>');}
 try{
  if(r==='clientDashboard')await renderDashboard(version);
  else if(r==='clientProjects'||r==='clientProjectsPublished'){if(r==='clientProjectsPublished'){go('clientProjects');return;}await renderClientProjects(version);}
  else if(r==='contractorFeed')await renderFeed(version);
  else if(r==='clientProjectDetail'||r==='clientAcceptedProject'){if(r==='clientAcceptedProject'){go('clientProjectDetail');return;}await renderProject(false,version);}
  else if(r==='contractorProject')await renderProject(true,version);
  else if(r==='contractorBid')await renderBid(version);
  else if(r==='quoteDetail')await renderQuote(version);
  else if(r==='contractorQuotes')await renderQuotes(version);
  else if(r==='quoteAccepted')await renderAccepted(version);
  else if(r==='clientMessages')await renderMessages(version);
  else if(r==='clientChat')await renderChat(version);
  else if(r==='profilePreview'||r==='businessProfile')await renderBusinessProfile(version);
  else if(r==='projectReview')review();
 }catch(e){if(version===routeVersion)pageError(err(e),true);}
}
function review(){const host=$('#projectReview .rd72-publish-page');let summary=byId('rd-live-review');if(!summary){summary=document.createElement('div');summary.id='rd-live-review';summary.className='rd-live-card';byId('rd72Publish').before(summary);}summary.innerHTML='<strong>'+esc(value('rd80ProjectName')||draft.type)+'</strong><p>'+esc(value('rd62Description'))+'</p><div class="rd-live-meta"><span>'+esc(draft.type)+'</span><span>'+esc(value('rd62City'))+'</span></div><p>'+esc(draft.budget)+' · '+esc(draft.timing)+'</p>';}
async function compressPhoto(file){required(file.type.startsWith('image/'),'Sélectionnez uniquement des images.');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));}finally{URL.revokeObjectURL(url);}}
let publicationAudio=null;
function preparePublicationAudio(){
 try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;
  if(!publicationAudio||publicationAudio.state==='closed')publicationAudio=new Audio();
  const ctx=publicationAudio;ctx.resume().catch(()=>{});
  // Unlock audio during the publish tap, before the network request (mobile Safari).
  const silent=ctx.createBufferSource();silent.buffer=ctx.createBuffer(1,1,ctx.sampleRate);silent.connect(ctx.destination);silent.start();
 }catch(e){}
}
function playPublicationSound(){
 try{const ctx=publicationAudio;if(!ctx||ctx.state!=='running')return;
  const start=ctx.currentTime+.02;
  [659.25,880,1108.73].forEach((frequency,i)=>{const tone=ctx.createOscillator(),gain=ctx.createGain(),at=start+i*.11;
   tone.type='sine';tone.frequency.value=frequency;gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(.07,at+.012);gain.gain.exponentialRampToValueAtTime(.001,at+.24);
   tone.connect(gain);gain.connect(ctx.destination);tone.onended=()=>{tone.disconnect();gain.disconnect();};tone.start(at);tone.stop(at+.26);
  });
 }catch(e){}
}
async function publish(){preparePublicationAudio();required(profile?.role==='client','Connectez-vous avec un compte client.');required(draft.service,'Choisissez le type de projet.');required(value('rd62Description').length>=10,'Décrivez les travaux en au moins 10 caractères.');required(draft.budget&&draft.timing,'Choisissez le budget et l’échéancier.');const location=city(value('rd62City')),files=[...byId('rd56Photos').files];required(files.length<=12,'Sélectionnez au maximum 12 photos.');required(!value('rd62Postal')||/^[A-Z]\d[A-Z][ -]?\d[A-Z]\d$/i.test(value('rd62Postal')),'Indiquez un code postal canadien valide.');
 const id=crypto.randomUUID();const p=await result(db.from('rd_projects').insert({id,client_id:user.id,title:value('rd80ProjectName')||draft.type,service:draft.service,description:value('rd62Description'),budget:draft.budget,timing:draft.timing,...location,postal:value('rd62Postal').toUpperCase()}).select().single());selectedProject=p;remember('project',p.id);
 let photoError=false;for(const file of files){try{const blob=await compressPhoto(file);required(blob,'Cette image ne peut pas être utilisée.');const path=p.id+'/'+crypto.randomUUID()+'.jpg';await result(db.storage.from('rd-project-photos').upload(path,blob,{contentType:'image/jpeg'}));await result(db.from('rd_project_photos').insert({project_id:p.id,path}));}catch(e){photoError=true;}}
 draft={};byId('rd80ProjectName').value='';byId('rd62Description').value='';byId('rd56Photos').value='';byId('rd56Preview').innerHTML='';byId('rd56Status').textContent='Aucune photo sélectionnée';go('clientProjectDetail');playPublicationSound();notify(photoError?'Projet publié. Certaines photos n’ont pas pu être envoyées.':'Projet publié : les entrepreneurs correspondant à vos services et à votre secteur peuvent le voir.');
}
async function accept(id){const q=await quote(id);required(q,'Soumission introuvable.');if(!confirm('Choisir cet entrepreneur pour '+money(q.amount)+' ? Les autres offres seront indiquées comme non retenues.'))return;await result(db.rpc('rd_accept_quote',{quote:id}));selectedQuote=await quote(id);remember('quote',id);go('quoteAccepted');}
async function progress(status){const p=await loadSelectedProject();const question=status==='completed'?'Confirmer que les travaux sont terminés ?':status==='archived'?'Archiver ce projet ? Il ne sera plus proposé aux entrepreneurs.':'Indiquer que les travaux ont commencé ?';if(!confirm(question))return;await result(db.rpc('rd_progress_project',{project:p.id,next_status:status}));selectedProject=await project(p.id);await render();notify('Statut du projet mis à jour.');}
function bind(){const businessScreen=document.createElement('section');businessScreen.id='businessProfile';businessScreen.className='screen';document.body.append(businessScreen);sharedRoutes.add('businessProfile');document.addEventListener('input',e=>{const form=e.target.closest('#rd-live-bid,#rd-live-chat-form');if(form)saveForm(form);});installPageTransitions();installQuoteNotifications();document.documentElement.classList.add('rd-live-app');
 document.querySelectorAll('.rd62-switch').forEach(a=>{a.textContent='Se déconnecter';a.href='#accueil';a.dataset.logout='1';});
 $('#pro1 .login button').onclick=()=>go('loginPro');
 $('#contractorFeed .rd58-filterbar a').textContent='Mes services ⚙';$('#contractorFeed .rd58-filterbar a').href='#services';
 byId('contractorFeed').querySelectorAll('nav a').forEach(a=>{if(a.textContent.trim()==='Messages')a.href='#clientMessages';});
 byId('clientDashboard').querySelectorAll('nav a').forEach(a=>{if(a.textContent.trim()==='Soumissions')a.href='#clientProjects';});
 document.querySelectorAll('[onclick*="RD72"],[onclick*="RD74"]').forEach(e=>e.removeAttribute('onclick'));
 const types=byId('rd63TypeOptions');types.innerHTML=Object.entries(services).map(([key,label])=>'<a href="#projectDetails" data-service="'+key+'"><b>⌂</b><span>'+esc(label)+'</span><i>→</i></a>').join('');
 byId('rd62Description').setAttribute('aria-label','Description des travaux');byId('rd62Description').maxLength=10000;byId('rd80ProjectName').maxLength=160;
 document.addEventListener('click',e=>{const a=e.target.closest('a,button');if(!a)return;const r=route();
  const run=fn=>{e.preventDefault();e.stopImmediatePropagation();void action(a,fn);};
  if(a.dataset.business){selectedBusiness=a.dataset.business;remember('business',selectedBusiness);businessEditing=false;}
  if(a.dataset.businessSave!==undefined){run(saveBusinessChanges);return;}
  if(a.dataset.businessEdit!==undefined){run(async()=>{portfolioEditing=null;businessEditing=a.dataset.businessEdit==='1';await render();});return;}
  if(a.dataset.portfolioEdit){run(async()=>{const row=businessPortfolio.find(p=>p.id===a.dataset.portfolioEdit);required(row,'Réalisation introuvable.');portfolioEditing=row.id;businessEditing=true;await render();});return;}
  if(a.dataset.logout){run(async()=>{await db.auth.signOut();user=null;profile=null;accountDetails=null;selectedProject=null;selectedQuote=null;clearQuoteNotice();go('accueil');});return;}
  if(a.dataset.account||a.matches('#clientDashboard .rd51-avatar')){e.preventDefault();notify(profile.display_name+' · '+profile.city+' · '+user.email);return;}
  if(a.dataset.refresh!==undefined){run(render);return;}
  if(a.dataset.projectTab){e.preventDefault();projectTab=a.dataset.projectTab;void render();return;}
  if(a.dataset.quoteTab){e.preventDefault();quoteTab=a.dataset.quoteTab;void render();return;}
  if(a.dataset.project){selectedProject={id:a.dataset.project};remember('project',a.dataset.project);}
  if(a.dataset.quote){selectedQuote={id:a.dataset.quote};remember('quote',a.dataset.quote);}
  if(a.dataset.accept){run(()=>accept(a.dataset.accept));return;}
  if(a.dataset.progress){run(()=>progress(a.dataset.progress));return;}
  if(a.dataset.service){draft={...draft,service:a.dataset.service,type:services[a.dataset.service]};}
  if(a.closest('#rd62BudgetOptions'))draft.budget=a.querySelector('span').textContent;
  if(a.closest('#rd62TimingOptions'))draft.timing=a.querySelector('span').textContent;
  if(a.matches('#client a.primary')){run(()=>signup('client'));return;}
  if(a.matches('#loginClient a.primary')){run(()=>login('client'));return;}
  if(a.matches('#loginPro a.primary')){run(()=>login('contractor'));return;}
  if(a.matches('#pro1 a.primary')){run(async()=>{credentials('contractor');required(value('rd-pro1-field-1')&&value('rd-pro1-field-2'),'Indiquez votre prénom et votre nom.');go('pro2');});return;}
  if(a.matches('#pro2 a.primary')){run(async()=>{required(value('rd-pro2-field-1'),'Indiquez le nom de votre entreprise.');go('services');});return;}
  if(a.matches('#services a.primary')){run(async()=>{required(selectedServices().length,'Choisissez au moins un service.');if(!value('rd-territory-field-1'))byId('rd-territory-field-1').value=value('rd-pro2-field-5');go('territory');});return;}
  if(a.matches('#territory a.primary')){run(async()=>{if(profile?.role==='contractor'){const p=readContractor(),details=p.account_details;delete p.role;delete p.account_details;profile=await result(db.from('rd_profiles').update(p).eq('id',user.id).select().single());accountDetails=await result(db.from('rd_account_details').upsert({id:user.id,...details}).select().single());go('building');notify('Services et territoire enregistrés.');}else await signup('contractor');});return;}
  if(a.matches('#profilePreview .mp-edit'))fillProfile();
  if(a.matches('#projectDetails .rd52-next')){run(async()=>{required(value('rd62Description').length>=10,'Décrivez les travaux en au moins 10 caractères.');go('projectBudget');});return;}
  if(a.matches('#projectLocation .rd52-next')){run(async()=>{city(value('rd62City'));go('projectReview');});return;}
  if(a.id==='rd72Publish'){run(publish);return;}
  if(a.matches('.forgot')){run(async()=>{const screen=a.closest('.screen'),email=screen.querySelector('input[type="email"]').value.trim();required(email,'Indiquez votre courriel pour recevoir le lien de réinitialisation.');await result(db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/#resetPassword'}));notify('Si ce compte existe, un lien de réinitialisation a été envoyé.');});return;}
  if(a.getAttribute('href')==='#newProject'&&['clientDashboard','clientProjects'].includes(r)){draft={};byId('rd80ProjectName').value='';byId('rd62Description').value='';byId('rd62City').value=profile.city;}
  if(a.getAttribute('href')==='#services'&&profile?.role==='contractor')fillProfile();
 },true);
 document.addEventListener('change',e=>{if(e.target.id==='rd-business-cover'&&profile?.role==='contractor'&&route()==='profilePreview')void previewCover(e.target);});
 document.addEventListener('input',e=>{if(e.target.id==='rd-cover-zoom'&&coverCrop){coverCrop.zoom=Math.max(1,Math.min(3,Number(e.target.value)));positionCover();}});
 document.addEventListener('click',e=>{if(e.target.closest('[data-cover-reset]')&&coverCrop){coverCrop.zoom=1;coverCrop.x=coverCrop.y=.5;byId('rd-cover-zoom').value='1';positionCover();}});
 document.addEventListener('pointerdown',e=>{const cover=e.target.closest('.rd-cover-cropping');if(!cover||!coverCrop||e.target.closest('.rd-business-cover-edit')||e.button!==0)return;e.preventDefault();coverDrag={pointer:e.pointerId,cover,startX:e.clientX,startY:e.clientY,x:coverCrop.x,y:coverCrop.y};cover.setPointerCapture?.(e.pointerId);});
 document.addEventListener('pointermove',e=>{if(!coverDrag||!coverCrop||coverDrag.pointer!==e.pointerId)return;e.preventDefault();const g=coverGeometry(coverCrop,coverDrag.cover);if(g.overflowX>0)coverCrop.x=Math.max(0,Math.min(1,coverDrag.x-(e.clientX-coverDrag.startX)/g.overflowX));if(g.overflowY>0)coverCrop.y=Math.max(0,Math.min(1,coverDrag.y-(e.clientY-coverDrag.startY)/g.overflowY));positionCover();},{passive:false});
 const finishCoverDrag=e=>{if(coverDrag?.pointer===e.pointerId)coverDrag=null;};document.addEventListener('pointerup',finishCoverDrag);document.addEventListener('pointercancel',finishCoverDrag);window.addEventListener('resize',positionCover);
 document.addEventListener('submit',e=>{if(!['rd-business-form','rd-portfolio-form','rd-live-bid','rd-live-chat-form','rd-live-reset'].includes(e.target.id))return;e.preventDefault();const form=e.target;void action(form.querySelector('button[type="submit"]')||form.querySelector('button'),async()=>{
  if(form.id==='rd-business-form'||form.id==='rd-portfolio-form'){await saveBusinessChanges();}
  else if(form.id==='rd-live-bid'){const owner=user.id,id=selectedProject?.id||recall('project'),key=formKey(form.id),row={project_id:id,contractor_id:owner,amount:Number(value('rd-bid-amount')),duration:value('rd-bid-duration'),start_date:value('rd-bid-date'),message:value('rd-bid-message')};required(row.amount>0&&row.amount<=9999999999,'Indiquez un montant valide.');required(row.duration&&row.start_date&&row.message.length>=10,'Complétez la durée, la date et le détail de votre offre.');const q=await result(db.from('rd_quotes').insert(row).select().single());formDrafts.delete(key);if(user?.id===owner&&route()==='contractorBid'&&(selectedProject?.id||recall('project'))===id){selectedQuote=q;remember('quote',q.id);go('quoteDetail');}notify('Soumission envoyée au client.');}
  else if(form.id==='rd-live-chat-form'){required(value('rd-live-message'),'Écrivez un message.');const owner=user.id,id=selectedQuote?.id||recall('quote'),body=value('rd-live-message'),key=formKey(form.id);await result(db.from('rd_messages').insert({quote_id:id,sender_id:owner,body}));if(formDrafts.get(key)?.['rd-live-message']===body)formDrafts.delete(key);if(route()==='clientChat'&&user?.id===owner&&(selectedQuote?.id||recall('quote'))===id){const input=byId('rd-live-message');if(input.value.trim()===body)input.value='';await chatMessages();byId('clientChat').scrollTop=byId('clientChat').scrollHeight;}}
  else {required(value('rd-live-new-password').length>=8,'Le mot de passe doit contenir au moins 8 caractères.');await result(db.auth.updateUser({password:value('rd-live-new-password')}));go(profile?.role==='contractor'?'contractorFeed':'clientDashboard');notify('Mot de passe mis à jour.');}
 });});
 window.addEventListener('hashchange',()=>{const guarded=guardSessionRoute();byId(route())&&(byId(route()).scrollTop=0);if(guarded||!transitionRouting)void render();});
 window.addEventListener('pageshow',()=>{if(guardSessionRoute())void render();});
 window.addEventListener('focus',()=>{if(busy||transitionRouting)return;if(['clientDashboard','contractorFeed','contractorQuotes','clientMessages','clientProjectDetail'].includes(route()))void render();});
 setInterval(()=>{if(document.hidden||busy||transitionRouting||!user)return;if(route()==='clientChat')void chatMessages().catch(()=>{});else if(['clientDashboard','contractorFeed','contractorQuotes','clientMessages','clientProjectDetail'].includes(route()))void render();},15000);
}
async function initialize(){try{cities=await fetch('/app/cities.json').then(r=>{if(!r.ok)throw Error('La liste des villes n’est pas disponible. Rechargez l’app.');return r.json();});const list=document.createElement('datalist');list.id='rd-city-list';list.innerHTML=cities.map(c=>'<option value="'+esc(c[0])+'"></option>').join('');document.body.append(list);['rd-signup-address-level2','rd-pro2-field-5','rd-territory-field-1','rd62City'].forEach(id=>byId(id).setAttribute('list',list.id));
 bind();const {data,error}=await db.auth.getSession();if(error)throw error;user=data.session?.user||null;if(user)await loadProfile();guardSessionRoute();fillProfile();void checkQuoteNotifications();
 db.auth.onAuthStateChange((event,session)=>{setTimeout(async()=>{try{const next=session?.user||null,same=next?.id===user?.id;if(same&&profile&&event!=='PASSWORD_RECOVERY')return;++routeVersion;renderedRoute='';clearQuoteNotice();formDrafts.clear();selectedBusiness=null;businessEditing=false;portfolioEditing=null;businessPortfolio=[];paint(byId('profilePreview'),'');paint(byId('businessProfile'),'');profile=null;accountDetails=null;user=next;selectedProject=null;selectedQuote=null;draft={};if(user)await loadProfile();else{profile=null;accountDetails=null;selectedProject=null;selectedQuote=null;}void checkQuoteNotifications();if(busy)return;if(event==='PASSWORD_RECOVERY'){shell('resetPassword','<h1 class="rd-live-heading">Nouveau mot de passe</h1><form id="rd-live-reset"><label for="rd-live-new-password">Mot de passe</label><input id="rd-live-new-password" type="password" autocomplete="new-password" minlength="8" required><button class="rd-live-button">Enregistrer →</button></form>');go('resetPassword');}else if(user&&(!route()||route().startsWith('access_token')||route()==='loginClient'||route()==='loginPro'))go(profile?.role==='contractor'?'contractorFeed':'clientDashboard');else await render();}catch(e){pageError(err(e));}},0);});
 if(user&&(!route()||route().startsWith('access_token')))go(profile?.role==='contractor'?'contractorFeed':'clientDashboard');else await render();
 }catch(e){notify(err(e));}}
 void initialize();
})();
