/* RénoDirect: authenticated marketplace flows. No demo projects or offers. */
(function(){
'use strict';
const db=window.supabase.createClient('https://qefpomgdknlcsavkritc.supabase.co','sb_publishable_qpOjNgQIyWPAwrvh73VSWA_vXIXvqQf');
const {services,inputServices,normalize,serviceKey}=window.RDCore;
const $=s=>document.querySelector(s), byId=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v).toLocaleString('fr-CA',{style:'currency',currency:'CAD'});
const labels={open:'Publié',accepted:'Entrepreneur choisi',in_progress:'Travaux en cours',completed:'Terminé',archived:'Archivé',pending:'En attente',declined:'Non retenue'};
let profileLoading=null;
let user=null,profile=null,accountDetails=null,cities=[],selectedProject=null,selectedQuote=null,routeVersion=0,busy=false,quoteTab='pending',projectTab='active',signupProfile=null;
let draft={service:'',type:'',budget:'',timing:''};
const contractorRoutes=new Set(['contractorFeed','contractorProject','contractorBid','contractorQuotes']);
const clientRoutes=new Set(['clientDashboard','newProject','projectDetails','projectBudget','projectTiming','projectLocation','projectReview','clientProjects','clientProjectsPublished','clientProjectDetail','clientAcceptedProject']);
const sharedRoutes=new Set(['quoteDetail','quoteAccepted','clientMessages','clientChat']);
const editingRoutes=new Set(['pro2','services','territory','building','profilePreview']);
function route(){return location.hash.slice(1).split('?')[0];}
function go(id){location.hash=id;}
function notify(message){let e=byId('rd-live-notice');if(!e){e=document.createElement('div');e.id='rd-live-notice';e.className='rd-live-notice';e.setAttribute('role','status');document.body.append(e);}e.textContent=message;clearTimeout(notify.timer);notify.timer=setTimeout(()=>e.remove(),6500);}
function err(e){const text=e?.message||'Connexion impossible. Réessayez.';if(/invalid login/i.test(text))return 'Courriel ou mot de passe incorrect.';if(/email not confirmed/i.test(text))return 'Confirmez votre courriel avant de vous connecter.';if(/rate limit|too many/i.test(text))return 'Trop de tentatives. Patientez un moment puis réessayez.';if(/already registered/i.test(text))return 'Ce courriel a déjà un compte. Connectez-vous.';if(/duplicate key/i.test(text))return 'Vous avez déjà envoyé une soumission pour ce projet.';if(/fetch|network/i.test(text))return 'Vérifiez votre connexion Internet et réessayez.';return text;}
function pageError(message){let page=byId(route());if(!page)return;let e=page.querySelector('.rd-live-error');if(!e){e=document.createElement('div');e.className='rd-live-error';e.setAttribute('role','alert');(page.querySelector('.rd-signup-card,.login-card,.rd52,.rd-live-detail,.rd58-shell')||page).append(e);}e.textContent=message;e.scrollIntoView({block:'nearest'});}
async function result(request){const {data,error}=await request;if(error)throw error;return data;}
async function action(button,fn){if(busy)return;busy=true;const old=button?.textContent;if(button){button.setAttribute('aria-disabled','true');button.textContent='Un instant…';}document.querySelectorAll('.rd-live-error').forEach(e=>e.remove());try{await fn();}catch(e){pageError(err(e));}finally{busy=false;if(button){button.removeAttribute('aria-disabled');button.textContent=old;}}}
const value=id=>byId(id)?.value.trim()||'';
function required(ok,message){if(!ok)throw Error(message);}
function city(v){const found=cities.find(c=>normalize(c[0])===normalize(v));required(found,'Choisissez votre ville dans les suggestions.');return {city:found[0],latitude:found[1],longitude:found[2]};}
function selectedServices(){return Object.entries(inputServices).filter(([id])=>byId(id).checked).map(([,key])=>key);}
function radius(){return Number(value('rd-territory-field-2')||$('#territory input[name="radius"]:checked')?.id.slice(1)||50);}
function readClient(){required(value('rd-signup-given-name')&&value('rd-signup-family-name'),'Indiquez votre prénom et votre nom.');city(value('rd-signup-address-level2'));return {role:'client',display_name:[value('rd-signup-given-name'),value('rd-signup-family-name')].join(' '),company_name:'',...city(value('rd-signup-address-level2')),services:[],radius_km:50,rbq:'',account_details:{phone:value('rd-signup-tel'),postal:value('rd-signup-postal-code')}};}
function readContractor(){required(value('rd-pro2-field-1'),'Indiquez le nom de votre entreprise.');required(selectedServices().length,'Choisissez au moins un service.');required(radius()>=1&&radius()<=300,'Le rayon doit être entre 1 et 300 km.');return {role:'contractor',display_name:[value('rd-pro1-field-1'),value('rd-pro1-field-2')].filter(Boolean).join(' ')||profile?.display_name||value('rd-pro2-field-2')||value('rd-pro2-field-1'),company_name:value('rd-pro2-field-2')||value('rd-pro2-field-1'),...city(value('rd-territory-field-1')),services:selectedServices(),radius_km:radius(),rbq:value('rd-pro2-field-7'),account_details:{phone:value('rd-pro2-field-3')||value('rd-pro1-field-4'),legal_company_name:value('rd-pro2-field-1'),address:value('rd-pro2-field-4'),postal:value('rd-pro2-field-6'),website:value('rd-pro2-field-8')}};}
function credentials(kind){const pro=kind==='contractor',email=value(pro?'rd-pro1-field-3':'rd-signup-email'),password=value(pro?'rd-pro1-field-5':'rd-signup-new-password'),confirm=value(pro?'rd-pro1-field-6':'rd-signup-confirm-password');required(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Indiquez un courriel valide.');required(password.length>=8,'Le mot de passe doit contenir au moins 8 caractères.');required(password===confirm,'Les deux mots de passe doivent être identiques.');return {email,password};}
async function signup(kind){const initial=kind==='client'?readClient():readContractor();if(kind==='client')required($('#client .terms input').checked,'Acceptez les conditions avant de créer votre compte.');const c=credentials(kind);signupProfile=initial;
 const {data,error}=await db.auth.signUp({...c,options:{emailRedirectTo:location.origin+'/',data:{initial_profile:initial}}});if(error)throw error;
 if(data.session){user=data.user;await loadProfile();go(kind==='client'?'clientDashboard':'building');}else{go(kind==='client'?'loginClient':'loginPro');notify('Compte créé. Confirmez votre courriel avec le lien reçu, puis connectez-vous.');}
 ['rd-signup-new-password','rd-signup-confirm-password','rd-pro1-field-5','rd-pro1-field-6'].forEach(id=>{if(byId(id))byId(id).value='';});
}
async function loadProfile(){if(profileLoading)return profileLoading;profileLoading=loadProfileOnce();try{return await profileLoading;}finally{profileLoading=null;}}
async function loadProfileOnce(){if(!user){profile=null;return;}
 profile=await result(db.from('rd_profiles').select('*').eq('id',user.id).maybeSingle());
 if(!profile){const pending=signupProfile||user.user_metadata?.initial_profile;if(pending){const allowed=['role','display_name','company_name','city','latitude','longitude','services','radius_km','rbq'];const row=Object.fromEntries(allowed.map(k=>[k,pending[k]]));profile=await result(db.from('rd_profiles').insert({id:user.id,...row}).select().single());signupProfile=null;}}
 if(profile){accountDetails=await result(db.from('rd_account_details').select('*').eq('id',user.id).maybeSingle());const initial=user.user_metadata?.initial_profile?.account_details;if(!accountDetails&&initial)accountDetails=await result(db.from('rd_account_details').insert({id:user.id,...initial}).select().single());}
}
async function login(kind){const screen=byId(kind==='client'?'loginClient':'loginPro'),email=screen.querySelector('input[type="email"]').value.trim(),password=screen.querySelector('input[type="password"]').value;required(email&&password,'Indiquez votre courriel et votre mot de passe.');const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;user=data.user;await loadProfile();required(profile,'Votre profil est incomplet. Complétez votre inscription.');if(profile.role!==kind){await db.auth.signOut();user=null;profile=null;throw Error('Ce compte est un compte '+(kind==='client'?'entrepreneur. Utilisez la connexion entrepreneur.':'client. Utilisez la connexion client.'));}screen.querySelector('input[type="password"]').value='';go(kind==='client'?'clientDashboard':'contractorFeed');}
function remember(key,id){if(user)localStorage.setItem('rd-live-'+user.id+'-'+key,id);}
function recall(key){return user?localStorage.getItem('rd-live-'+user.id+'-'+key):null;}
async function project(id){if(!id)return null;return await result(db.from('rd_projects').select('*').eq('id',id).maybeSingle());}
async function quote(id){if(!id)return null;return await result(db.from('rd_quotes').select('*').eq('id',id).maybeSingle());}
function empty(text){return '<div class="rd-live-empty">'+esc(text)+'</div>';}
function card(p,link,extra=''){return '<a class="rd-live-card" href="#'+link+'" data-project="'+p.id+'"><div class="rd-live-meta"><span class="rd-live-status">'+esc(labels[p.status])+'</span><span>'+esc(p.city)+'</span></div><h3>'+esc(p.title)+'</h3><p>'+esc(p.description.slice(0,180))+'</p><div class="rd-live-meta"><span>'+esc(services[p.service])+'</span><span>'+esc(p.budget)+'</span></div>'+extra+'</a>';}
function back(id,text='Retour'){return '<a href="#'+id+'">← '+esc(text)+'</a>';}
function shell(id,content){byId(id).innerHTML='<div class="rd-live-detail">'+content+'</div>';}
function nav(pro){return '<nav class="rd-live-nav"><a href="#'+(pro?'contractorFeed':'clientDashboard')+'">Accueil</a><a href="#'+(pro?'contractorQuotes':'clientProjects')+'">'+(pro?'Soumissions':'Projets')+'</a><a href="#clientMessages">Messages</a><a href="#'+(pro?'profilePreview':'clientDashboard')+'" '+(pro?'':'data-account="1"')+'>Profil</a></nav>';}
function person(p){return p?.company_name||p?.display_name||'Entrepreneur';}
async function profiles(ids){if(!ids.length)return {};const rows=await result(db.from('rd_profiles').select('*').in('id',[...new Set(ids)]));return Object.fromEntries(rows.map(p=>[p.id,p]));}
async function ownProjects(){return result(db.from('rd_projects').select('*').eq('client_id',user.id).order('created_at',{ascending:false}));}
async function ownQuotes(){return result(db.from('rd_quotes').select('*').eq('contractor_id',user.id).order('created_at',{ascending:false}));}
async function renderDashboard(version){const ps=await ownProjects();if(version!==routeVersion)return;const active=ps.filter(p=>!['archived','completed'].includes(p.status));$('#clientDashboard .rd51-head h1').textContent='Bonjour, '+profile.display_name.split(' ')[0]+'.';$('#clientDashboard .rd51-avatar').textContent=profile.display_name.split(' ').map(n=>n[0]).join('').slice(0,2);
 const section=$('#clientDashboard .rd51-section');section.querySelector('.rd51-section-title>span').textContent=active.length+' actif'+(active.length>1?'s':'');section.querySelectorAll('.rd51-project,.rd-live-card,.rd-live-empty').forEach(e=>e.remove());section.insertAdjacentHTML('beforeend',active.length?active.slice(0,3).map(p=>card(p,'clientProjectDetail')).join(''):empty('Aucun projet publié. Décrivez vos travaux pour recevoir des soumissions.'));
 const activity=$('#clientDashboard .rd79-activity');if(activity)activity.innerHTML='<div class="rd51-section-title"><h2>Activité récente</h2><button class="rd-live-refresh" data-refresh>Actualiser</button></div>'+ (ps.length?ps.slice(0,2).map(p=>'<a class="rd-live-card" href="#clientProjectDetail" data-project="'+p.id+'"><strong>'+esc(p.title)+'</strong><p>'+esc(labels[p.status])+'</p></a>').join(''):empty('Vos projets et leurs mises à jour apparaîtront ici.'));
 const link=$('#clientDashboard .rd51-quick a[href="#clientProjectDetail"]')||[...byId('clientDashboard').querySelectorAll('a')].find(a=>a.textContent.includes('Soumissions')&&a.closest('nav')===null);if(link)link.setAttribute('href','#clientProjects');byId('rd79PublishedActivity')?.remove();
}
async function renderClientProjects(version){const ps=await ownProjects();if(version!==routeVersion)return;const shown=ps.filter(p=>projectTab==='active'?!['completed','archived'].includes(p.status):p.status===projectTab);shell('clientProjects',back('clientDashboard')+'<h1 class="rd-live-heading">Mes projets</h1><div class="rd-live-tabs"><button data-project-tab="active" class="'+(projectTab==='active'?'active':'')+'">En cours</button><button data-project-tab="completed" class="'+(projectTab==='completed'?'active':'')+'">Terminés</button><button data-project-tab="archived" class="'+(projectTab==='archived'?'active':'')+'">Archivés</button></div>'+(shown.length?shown.map(p=>card(p,'clientProjectDetail')).join(''):empty('Aucun projet dans cette catégorie.'))+'<a class="rd-live-button" href="#newProject">Créer un projet →</a>'+nav(false));}
async function renderFeed(version){const ps=await result(db.from('rd_projects').select('*').eq('status','open').order('created_at',{ascending:false}));if(version!==routeVersion)return;byId('rd87MatchCount').textContent=ps.length;byId('rd62LiveProjects').innerHTML=ps.length?ps.map(p=>card(p,'contractorProject')).join(''):empty('Aucun projet correspondant à vos services et à votre territoire pour le moment.');$('#contractorFeed .rd58-prohead h1').textContent='Bonjour, '+profile.display_name.split(' ')[0]+'.';$('#contractorFeed .rd58-why p').textContent='Services : '+profile.services.map(s=>services[s]).join(', ')+'. Territoire : '+profile.city+' + '+profile.radius_km+' km. Distances estimées entre centres des villes.';}
async function loadSelectedProject(){const id=selectedProject?.id||recall('project');selectedProject=await project(id);required(selectedProject,'Projet introuvable ou inaccessible à votre entreprise.');return selectedProject;}
async function loadSelectedQuote(){const id=selectedQuote?.id||recall('quote');selectedQuote=await quote(id);required(selectedQuote,'Soumission introuvable ou inaccessible.');return selectedQuote;}
async function photoHTML(p){const photos=await result(db.from('rd_project_photos').select('path').eq('project_id',p.id));if(!photos.length)return '';const signed=await result(db.storage.from('rd-project-photos').createSignedUrls(photos.map(x=>x.path),3600));return '<div class="rd-live-photo-grid">'+signed.filter(x=>x.signedUrl).map(x=>'<a href="'+esc(x.signedUrl)+'" target="_blank" rel="noopener"><img src="'+esc(x.signedUrl)+'" alt="Photo du projet"></a>').join('')+'</div>';}
async function renderProject(pro,version){const p=await loadSelectedProject(),qs=pro?[]:await result(db.from('rd_quotes').select('*').eq('project_id',p.id).order('created_at',{ascending:false}));const names=await profiles(qs.map(q=>q.contractor_id)),photos=await photoHTML(p);if(version!==routeVersion)return;let content=back(pro?'contractorFeed':'clientProjects')+'<h1 class="rd-live-heading">'+esc(p.title)+'</h1><div class="rd-live-meta"><span class="rd-live-status">'+esc(labels[p.status])+'</span><span>'+esc(p.city)+'</span></div><div class="rd-live-card"><strong>'+esc(services[p.service])+'</strong><p>'+esc(p.description)+'</p><div class="rd-live-meta"><span>'+esc(p.budget)+'</span><span>'+esc(p.timing)+'</span></div></div>'+photos;
 if(pro){const sent=await result(db.from('rd_quotes').select('id').eq('project_id',p.id).eq('contractor_id',user.id).maybeSingle());content+=p.status==='open'&&!sent?'<a class="rd-live-button" href="#contractorBid">Préparer une soumission →</a>':sent?'<a class="rd-live-button" href="#quoteDetail" data-quote="'+sent.id+'">Consulter ma soumission →</a>':empty('Ce projet n’accepte plus de soumissions.');}
 else {content+='<h2>Soumissions reçues ('+qs.length+')</h2>'+(qs.length?qs.map(q=>quoteCard(q,names[q.contractor_id])).join(''):empty('Aucune soumission pour le moment. Les entrepreneurs correspondant à votre projet peuvent maintenant le consulter.'));if(['accepted','in_progress'].includes(p.status))content+='<button class="rd-live-button" data-progress="'+(p.status==='accepted'?'in_progress':'completed')+'">'+(p.status==='accepted'?'Indiquer le début des travaux':'Confirmer que les travaux sont terminés')+'</button>';if(p.status==='open')content+='<button class="rd-live-button secondary" data-progress="archived">Archiver le projet</button>';}
 shell(pro?'contractorProject':'clientProjectDetail',content);
}
function quoteCard(q,who,p){return '<a class="rd-live-card" href="#quoteDetail" data-quote="'+q.id+'"><div class="rd-live-meta"><strong>'+esc(who?person(who):p?.title||'Soumission')+'</strong><span class="rd-live-status">'+esc(labels[p?.status==='completed'?'completed':q.status])+'</span></div><h3>'+money(q.amount)+'</h3><p>'+esc(q.duration)+' · Début : '+esc(q.start_date)+'</p></a>';}
async function renderQuote(version){const q=await loadSelectedQuote(),p=await project(q.project_id);required(p,'Ce projet n’est plus accessible.');selectedProject=p;remember('project',p.id);const names=await profiles([q.contractor_id,p.client_id]);if(version!==routeVersion)return;
 let content=back(profile.role==='client'?'clientProjectDetail':'contractorQuotes')+'<span class="rd-live-status">'+esc(labels[p.status==='completed'?'completed':q.status])+'</span><h1 class="rd-live-heading">'+esc(person(names[q.contractor_id]))+'</h1><p class="rd-live-copy">'+esc(p.title)+'</p><div class="rd-live-card"><h2>'+money(q.amount)+'</h2><p>Durée : '+esc(q.duration)+'<br>Début proposé : '+esc(q.start_date)+'</p><p>'+esc(q.message)+'</p></div><a class="rd-live-button secondary" href="#clientChat" data-quote="'+q.id+'">Discuter →</a>';
 if(profile.role==='client'&&q.status==='pending'&&p.status==='open')content+='<button class="rd-live-button" data-accept="'+q.id+'">Choisir cet entrepreneur →</button><p class="rd-live-copy">Les autres soumissions seront indiquées comme non retenues. Confirmez les modalités avec l’entrepreneur avant le début des travaux.</p>';
 if(q.status==='accepted'&&p.status==='accepted')content+='<button class="rd-live-button" data-progress="in_progress">Indiquer le début des travaux</button>';
 if(profile.role==='client'&&q.status==='accepted'&&p.status==='in_progress')content+='<button class="rd-live-button" data-progress="completed">Confirmer que les travaux sont terminés</button>';
 const contractor=names[q.contractor_id];if(contractor)content+='<div class="rd-live-card"><h2>Entreprise</h2><p>'+esc(contractor.city)+' · '+contractor.services.map(s=>esc(services[s])).join(', ')+'</p><p>Licence RBQ déclarée : '+esc(contractor.rbq||'Non renseignée')+'</p></div>';
 shell('quoteDetail',content);
}
async function renderBid(version){const p=await loadSelectedProject();required(p.status==='open','Ce projet n’accepte plus de soumissions.');if(version!==routeVersion)return;shell('contractorBid',back('contractorProject')+'<p class="rd-live-copy">'+esc(p.title)+'</p><h1 class="rd-live-heading">Votre soumission</h1><form id="rd-live-bid"><label for="rd-bid-amount">Prix total proposé ($)</label><input id="rd-bid-amount" type="number" min="0.01" step="0.01" max="9999999999" required inputmode="decimal"><label for="rd-bid-duration">Durée estimée des travaux</label><input id="rd-bid-duration" placeholder="Ex. 2 jours ou 3 semaines" maxlength="120" required><label for="rd-bid-date">Date de début possible</label><input id="rd-bid-date" type="date" required><label for="rd-bid-message">Détail de l’offre et message au client</label><textarea id="rd-bid-message" minlength="10" maxlength="10000" placeholder="Expliquez les travaux inclus, les exclusions et vos disponibilités." required></textarea><p class="rd-live-copy">Précisez dans votre offre si les taxes sont incluses.</p><button class="rd-live-button" type="submit">Envoyer la soumission →</button></form>');}
async function renderQuotes(version){const qs=await ownQuotes(),ps=qs.length?await result(db.from('rd_projects').select('*').in('id',qs.map(q=>q.project_id))):[];if(version!==routeVersion)return;const pm=Object.fromEntries(ps.map(p=>[p.id,p]));const shown=qs.filter(q=>quoteTab==='completed'?pm[q.project_id]?.status==='completed':q.status===quoteTab&&pm[q.project_id]?.status!=='completed');shell('contractorQuotes',back('contractorFeed')+'<h1 class="rd-live-heading">Mes soumissions</h1><div class="rd-live-tabs">'+[['pending','En attente'],['accepted','Acceptées'],['completed','Terminées'],['declined','Non retenues']].map(([k,t])=>'<button data-quote-tab="'+k+'" class="'+(quoteTab===k?'active':'')+'">'+t+'</button>').join('')+'</div>'+(shown.length?shown.map(q=>quoteCard(q,null,pm[q.project_id])).join(''):empty('Aucune soumission dans cette catégorie.'))+nav(true));}
async function renderAccepted(version){const q=await loadSelectedQuote(),p=await project(q.project_id);if(version!==routeVersion)return;shell('quoteAccepted',back('clientProjectDetail')+'<h1 class="rd-live-heading">Entrepreneur choisi.</h1><p class="rd-live-copy">Le projet « '+esc(p.title)+' » est maintenant attribué. Retrouvez votre soumission et la conversation pour organiser les travaux.</p><a href="#quoteDetail" class="rd-live-button">Voir la soumission →</a><a href="#clientChat" class="rd-live-button secondary">Discuter →</a>');}
async function renderMessages(version){const qs=await result(db.from('rd_quotes').select('*').order('created_at',{ascending:false})),ps=qs.length?await result(db.from('rd_projects').select('*').in('id',qs.map(q=>q.project_id))):[],names=await profiles(qs.map(q=>profile.role==='client'?q.contractor_id:ps.find(p=>p.id===q.project_id)?.client_id).filter(Boolean));if(version!==routeVersion)return;
 shell('clientMessages',back(profile.role==='client'?'clientDashboard':'contractorFeed')+'<h1 class="rd-live-heading">Messages</h1>'+(qs.length?qs.map(q=>{const p=ps.find(x=>x.id===q.project_id),other=names[profile.role==='client'?q.contractor_id:p?.client_id];return '<a class="rd-live-card" href="#clientChat" data-quote="'+q.id+'"><strong>'+esc(person(other))+'</strong><p>'+esc(p?.title||'Projet')+'</p><span class="rd-live-status">'+esc(labels[q.status])+'</span></a>';}).join(''):empty('Vos conversations apparaîtront après l’envoi d’une soumission.'))+nav(profile.role==='contractor'));}
async function chatMessages(){const id=selectedQuote?.id||recall('quote');if(!id||!byId('rd-live-chat-messages'))return;const rows=await result(db.from('rd_messages').select('*').eq('quote_id',id).order('created_at'));if(route()!=='clientChat')return;const host=byId('rd-live-chat-messages'),current=byId('clientChat'),bottom=current.scrollHeight-current.scrollTop-current.clientHeight<100;host.innerHTML=rows.length?rows.map(m=>'<div class="rd-live-bubble '+(m.sender_id===user.id?'mine':'')+'">'+esc(m.body)+'<small>'+new Date(m.created_at).toLocaleString('fr-CA')+'</small></div>').join(''):empty('Commencez la conversation pour préciser les travaux et vos disponibilités.');if(bottom)current.scrollTop=current.scrollHeight;}
async function renderChat(version){const q=await loadSelectedQuote(),p=await project(q.project_id);if(version!==routeVersion)return;shell('clientChat',back('clientMessages')+'<h1 class="rd-live-heading">'+esc(p?.title||'Conversation')+'</h1><a href="#quoteDetail">Voir la soumission →</a><div id="rd-live-chat-messages"></div><form id="rd-live-chat-form"><label for="rd-live-message">Votre message</label><textarea id="rd-live-message" maxlength="4000" required placeholder="Écrivez votre message…"></textarea><button class="rd-live-button" type="submit">Envoyer →</button></form>');await chatMessages();}
function renderProfile(){if(!profile)return;const p=profile;$('#profilePreview .mp-company h3').textContent=person(p);$('#profilePreview .mp-company p').textContent=p.city+' · Entrepreneur';$('#profilePreview .mp-avatar').textContent=person(p).split(' ').map(n=>n[0]).join('').slice(0,2);const stats=byId('profilePreview').querySelectorAll('.mp-stat strong');stats[1].textContent=p.radius_km+' km';stats[2].textContent=p.services.length;$('#profilePreview .mp-chips').innerHTML=p.services.map(k=>'<span class="mp-chip">'+esc(services[k])+'</span>').join('');const area=$('#profilePreview .mp-area-copy');area.querySelector('strong').textContent=p.city;area.querySelector('span').textContent='Rayon estimé de '+p.radius_km+' km entre centres des villes';const lic=byId('profilePreview').querySelectorAll('.mp-license');lic[0].querySelector('strong').textContent='Licence RBQ déclarée';lic[0].querySelector('span').textContent=p.rbq||'Non renseignée';lic[1].querySelector('span').textContent=person(p)+' · '+p.city;byId('profilePreview').querySelectorAll('.mp-section-head').forEach(e=>{if(e.querySelector('h4')?.textContent==='Zone de service')e.querySelector('span').textContent=p.city+' + '+p.radius_km+' km';});$('#profilePreview .mp-badge').textContent='PROFIL PROFESSIONNEL';let credit=byId('rd-geographic-credit');if(!credit){credit=document.createElement('p');credit.id='rd-geographic-credit';credit.className='rd-live-copy';credit.innerHTML='Distances approximatives · <a href="https://www.geonames.org/" target="_blank" rel="noopener">GeoNames</a>';byId('profilePreview').querySelector('.modern-profile').append(credit);}[...byId('profilePreview').querySelectorAll('h4')].find(e=>e.textContent==='Informations vérifiées').textContent='Informations de l’entreprise';}
function fillProfile(){if(profile?.role!=='contractor')return;const p=profile;byId('rd-pro2-field-1').value=accountDetails?.legal_company_name||p.company_name;byId('rd-pro2-field-2').value=p.company_name;Object.entries({'rd-pro2-field-3':'phone','rd-pro2-field-4':'address','rd-pro2-field-6':'postal','rd-pro2-field-8':'website'}).forEach(([id,k])=>byId(id).value=accountDetails?.[k]||'');byId('rd-pro2-field-5').value=p.city;byId('rd-pro2-field-7').value=p.rbq;byId('rd-territory-field-1').value=p.city;byId('rd-territory-field-2').value=p.radius_km;Object.entries(inputServices).forEach(([id,k])=>byId(id).checked=p.services.includes(k));}
async function render(){const r=route(),version=++routeVersion;if(!r||r==='intro'||r==='accueil'||r.startsWith('access_token'))return;
 const requiredRole=(contractorRoutes.has(r)||r==='profilePreview'||r==='building')?'contractor':clientRoutes.has(r)?'client':null;
 if(requiredRole||sharedRoutes.has(r)||r==='profilePreview'||r==='building'){
  if(!user||!profile){go(requiredRole==='contractor'||['profilePreview','building'].includes(r)?'loginPro':'loginClient');return;}
  if(requiredRole&&profile.role!==requiredRole){notify('Ce menu appartient à un compte '+(requiredRole==='client'?'client':'entrepreneur')+'.');go(profile.role==='client'?'clientDashboard':'contractorFeed');return;}
 }
 try{
  if(r==='clientDashboard')await renderDashboard(version);
  else if(r==='clientProjects'||r==='clientProjectsPublished'){if(r==='clientProjectsPublished'){go('clientProjects');return;}await renderClientProjects(version);}
  else if(r==='contractorFeed')await renderFeed(version);
  else if(r==='clientProjectDetail'||r==='clientAcceptedProject'){if(r==='clientAcceptedProject'){go('clientProjectDetail');return;}await renderProject(false,version);}
  else if(r==='contractorProject')await renderProject(true,version);
  else if(r==='contractorBid')await renderBid(version);
  else if(r==='quoteDetail')await renderQuote(version);
  else if(r==='contractorQuotes')await renderQuotes(version);
  else if(r==='quoteAccepted')await renderAccepted(version);
  else if(r==='clientMessages')await renderMessages(version);
  else if(r==='clientChat')await renderChat(version);
  else if(r==='profilePreview')renderProfile();
  else if(r==='projectReview')review();
 }catch(e){if(version===routeVersion)pageError(err(e));}
}
function review(){const host=$('#projectReview .rd72-publish-page');let summary=byId('rd-live-review');if(!summary){summary=document.createElement('div');summary.id='rd-live-review';summary.className='rd-live-card';byId('rd72Publish').before(summary);}summary.innerHTML='<strong>'+esc(value('rd80ProjectName')||draft.type)+'</strong><p>'+esc(value('rd62Description'))+'</p><div class="rd-live-meta"><span>'+esc(draft.type)+'</span><span>'+esc(value('rd62City'))+'</span></div><p>'+esc(draft.budget)+' · '+esc(draft.timing)+'</p>';}
async function compressPhoto(file){required(file.type.startsWith('image/'),'Sélectionnez uniquement des images.');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));}finally{URL.revokeObjectURL(url);}}
async function publish(){required(profile?.role==='client','Connectez-vous avec un compte client.');required(draft.service,'Choisissez le type de projet.');required(value('rd62Description').length>=10,'Décrivez les travaux en au moins 10 caractères.');required(draft.budget&&draft.timing,'Choisissez le budget et l’échéancier.');const location=city(value('rd62City')),files=[...byId('rd56Photos').files];required(files.length<=12,'Sélectionnez au maximum 12 photos.');required(!value('rd62Postal')||/^[A-Z]\d[A-Z][ -]?\d[A-Z]\d$/i.test(value('rd62Postal')),'Indiquez un code postal canadien valide.');
 const id=crypto.randomUUID();const p=await result(db.from('rd_projects').insert({id,client_id:user.id,title:value('rd80ProjectName')||draft.type,service:draft.service,description:value('rd62Description'),budget:draft.budget,timing:draft.timing,...location,postal:value('rd62Postal').toUpperCase()}).select().single());selectedProject=p;remember('project',p.id);
 let photoError=false;for(const file of files){try{const blob=await compressPhoto(file);required(blob,'Cette image ne peut pas être utilisée.');const path=p.id+'/'+crypto.randomUUID()+'.jpg';await result(db.storage.from('rd-project-photos').upload(path,blob,{contentType:'image/jpeg'}));await result(db.from('rd_project_photos').insert({project_id:p.id,path}));}catch(e){photoError=true;}}
 draft={};byId('rd80ProjectName').value='';byId('rd62Description').value='';byId('rd56Photos').value='';byId('rd56Preview').innerHTML='';byId('rd56Status').textContent='Aucune photo sélectionnée';go('clientProjectDetail');notify(photoError?'Projet publié. Certaines photos n’ont pas pu être envoyées.':'Projet publié : les entrepreneurs correspondant à vos services et à votre secteur peuvent le voir.');
}
async function accept(id){const q=await quote(id);required(q,'Soumission introuvable.');if(!confirm('Choisir cet entrepreneur pour '+money(q.amount)+' ? Les autres offres seront indiquées comme non retenues.'))return;await result(db.rpc('rd_accept_quote',{quote:id}));selectedQuote=await quote(id);remember('quote',id);go('quoteAccepted');}
async function progress(status){const p=await loadSelectedProject();const question=status==='completed'?'Confirmer que les travaux sont terminés ?':status==='archived'?'Archiver ce projet ? Il ne sera plus proposé aux entrepreneurs.':'Indiquer que les travaux ont commencé ?';if(!confirm(question))return;await result(db.rpc('rd_progress_project',{project:p.id,next_status:status}));selectedProject=await project(p.id);await render();notify('Statut du projet mis à jour.');}
function bind(){document.documentElement.classList.add('rd-live-app');
 document.querySelectorAll('.rd62-switch').forEach(a=>{a.textContent='Se déconnecter';a.href='#accueil';a.dataset.logout='1';});
 $('#pro1 .login button').onclick=()=>go('loginPro');
 $('#contractorFeed .rd58-filterbar a').textContent='Mes services ⚙';$('#contractorFeed .rd58-filterbar a').href='#services';
 byId('contractorFeed').querySelectorAll('nav a').forEach(a=>{if(a.textContent.trim()==='Messages')a.href='#clientMessages';});
 byId('clientDashboard').querySelectorAll('nav a').forEach(a=>{if(a.textContent.trim()==='Soumissions')a.href='#clientProjects';});
 document.querySelectorAll('[onclick*="RD72"],[onclick*="RD74"]').forEach(e=>e.removeAttribute('onclick'));
 const types=byId('rd63TypeOptions');types.innerHTML=Object.entries(services).map(([key,label])=>'<a href="#projectDetails" data-service="'+key+'"><b>⌂</b><span>'+esc(label)+'</span><i>→</i></a>').join('');
 byId('rd62Description').setAttribute('aria-label','Description des travaux');byId('rd62Description').maxLength=10000;byId('rd80ProjectName').maxLength=160;
 document.addEventListener('click',e=>{const a=e.target.closest('a,button');if(!a)return;const r=route();
  const run=fn=>{e.preventDefault();e.stopImmediatePropagation();void action(a,fn);};
  if(a.dataset.logout){run(async()=>{await db.auth.signOut();user=null;profile=null;accountDetails=null;selectedProject=null;selectedQuote=null;go('accueil');});return;}
  if(a.dataset.account||a.matches('#clientDashboard .rd51-avatar')){e.preventDefault();notify(profile.display_name+' · '+profile.city+' · '+user.email);return;}
  if(a.dataset.refresh!==undefined){run(render);return;}
  if(a.dataset.projectTab){e.preventDefault();projectTab=a.dataset.projectTab;void render();return;}
  if(a.dataset.quoteTab){e.preventDefault();quoteTab=a.dataset.quoteTab;void render();return;}
  if(a.dataset.project){selectedProject={id:a.dataset.project};remember('project',a.dataset.project);}
  if(a.dataset.quote){selectedQuote={id:a.dataset.quote};remember('quote',a.dataset.quote);}
  if(a.dataset.accept){run(()=>accept(a.dataset.accept));return;}
  if(a.dataset.progress){run(()=>progress(a.dataset.progress));return;}
  if(a.dataset.service){draft={...draft,service:a.dataset.service,type:services[a.dataset.service]};}
  if(a.closest('#rd62BudgetOptions'))draft.budget=a.querySelector('span').textContent;
  if(a.closest('#rd62TimingOptions'))draft.timing=a.querySelector('span').textContent;
  if(a.matches('#client a.primary')){run(()=>signup('client'));return;}
  if(a.matches('#loginClient a.primary')){run(()=>login('client'));return;}
  if(a.matches('#loginPro a.primary')){run(()=>login('contractor'));return;}
  if(a.matches('#pro1 a.primary')){run(async()=>{credentials('contractor');required(value('rd-pro1-field-1')&&value('rd-pro1-field-2'),'Indiquez votre prénom et votre nom.');go('pro2');});return;}
  if(a.matches('#pro2 a.primary')){run(async()=>{required(value('rd-pro2-field-1'),'Indiquez le nom de votre entreprise.');go('services');});return;}
  if(a.matches('#services a.primary')){run(async()=>{required(selectedServices().length,'Choisissez au moins un service.');if(!value('rd-territory-field-1'))byId('rd-territory-field-1').value=value('rd-pro2-field-5');go('territory');});return;}
  if(a.matches('#territory a.primary')){run(async()=>{if(profile?.role==='contractor'){const p=readContractor(),details=p.account_details;delete p.role;delete p.account_details;profile=await result(db.from('rd_profiles').update(p).eq('id',user.id).select().single());accountDetails=await result(db.from('rd_account_details').upsert({id:user.id,...details}).select().single());go('building');notify('Services et territoire enregistrés.');}else await signup('contractor');});return;}
  if(a.matches('#profilePreview .mp-edit'))fillProfile();
  if(a.matches('#projectDetails .rd52-next')){run(async()=>{required(value('rd62Description').length>=10,'Décrivez les travaux en au moins 10 caractères.');go('projectBudget');});return;}
  if(a.matches('#projectLocation .rd52-next')){run(async()=>{city(value('rd62City'));go('projectReview');});return;}
  if(a.id==='rd72Publish'){run(publish);return;}
  if(a.matches('.forgot')){run(async()=>{const screen=a.closest('.screen'),email=screen.querySelector('input[type="email"]').value.trim();required(email,'Indiquez votre courriel pour recevoir le lien de réinitialisation.');await result(db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/#resetPassword'}));notify('Si ce compte existe, un lien de réinitialisation a été envoyé.');});return;}
  if(a.getAttribute('href')==='#newProject'&&['clientDashboard','clientProjects'].includes(r)){draft={};byId('rd80ProjectName').value='';byId('rd62Description').value='';byId('rd62City').value=profile.city;}
  if(a.getAttribute('href')==='#services'&&profile?.role==='contractor')fillProfile();
 },true);
 document.addEventListener('submit',e=>{if(!['rd-live-bid','rd-live-chat-form','rd-live-reset'].includes(e.target.id))return;e.preventDefault();const form=e.target;void action(form.querySelector('button'),async()=>{
  if(form.id==='rd-live-bid'){const p=await loadSelectedProject();const q=await result(db.from('rd_quotes').insert({project_id:p.id,contractor_id:user.id,amount:Number(value('rd-bid-amount')),duration:value('rd-bid-duration'),start_date:value('rd-bid-date'),message:value('rd-bid-message')}).select().single());selectedQuote=q;remember('quote',q.id);go('quoteDetail');notify('Soumission envoyée au client.');}
  else if(form.id==='rd-live-chat-form'){required(value('rd-live-message'),'Écrivez un message.');const q=await loadSelectedQuote();await result(db.from('rd_messages').insert({quote_id:q.id,sender_id:user.id,body:value('rd-live-message')}));byId('rd-live-message').value='';await chatMessages();byId('clientChat').scrollTop=byId('clientChat').scrollHeight;}
  else {required(value('rd-live-new-password').length>=8,'Le mot de passe doit contenir au moins 8 caractères.');await result(db.auth.updateUser({password:value('rd-live-new-password')}));go(profile?.role==='contractor'?'contractorFeed':'clientDashboard');notify('Mot de passe mis à jour.');}
 });});
 window.addEventListener('hashchange',()=>{byId(route())&&(byId(route()).scrollTop=0);void render();});
 window.addEventListener('focus',()=>{if(['clientDashboard','contractorFeed','contractorQuotes','clientMessages','clientProjectDetail'].includes(route()))void render();});
 setInterval(()=>{if(document.hidden||busy||!user)return;if(route()==='clientChat')void chatMessages().catch(()=>{});else if(['clientDashboard','contractorFeed','contractorQuotes','clientMessages','clientProjectDetail'].includes(route()))void render();},15000);
}
async function initialize(){try{cities=await fetch('/app/cities.json').then(r=>{if(!r.ok)throw Error('La liste des villes n’est pas disponible. Rechargez l’app.');return r.json();});const list=document.createElement('datalist');list.id='rd-city-list';list.innerHTML=cities.map(c=>'<option value="'+esc(c[0])+'"></option>').join('');document.body.append(list);['rd-signup-address-level2','rd-pro2-field-5','rd-territory-field-1','rd62City'].forEach(id=>byId(id).setAttribute('list',list.id));
 bind();const {data,error}=await db.auth.getSession();if(error)throw error;user=data.session?.user||null;if(user)await loadProfile();fillProfile();
 db.auth.onAuthStateChange((event,session)=>{setTimeout(async()=>{try{user=session?.user||null;if(user)await loadProfile();else{profile=null;accountDetails=null;selectedProject=null;selectedQuote=null;}if(busy)return;if(event==='PASSWORD_RECOVERY'){shell('resetPassword','<h1 class="rd-live-heading">Nouveau mot de passe</h1><form id="rd-live-reset"><label for="rd-live-new-password">Mot de passe</label><input id="rd-live-new-password" type="password" autocomplete="new-password" minlength="8" required><button class="rd-live-button">Enregistrer →</button></form>');go('resetPassword');}else if(user&&(!route()||route().startsWith('access_token')||route()==='loginClient'||route()==='loginPro'))go(profile?.role==='contractor'?'contractorFeed':'clientDashboard');else await render();}catch(e){pageError(err(e));}},0);});
 if(user&&(!route()||route().startsWith('access_token')))go(profile?.role==='contractor'?'contractorFeed':'clientDashboard');else await render();
 }catch(e){notify(err(e));}}
 void initialize();
})();
